### ISSUE TITLE
fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by NaldoDj** [harbour/core#102]
```
D:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -ohbznet.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../hbznet.c
..\..\..\..\..\src\rtl\obj\win\mingw64\../../../hbznet.c:59:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
win-make[3]: *** [..\..\..\..\..\src\rtl\obj\win\mingw64\hbznet.o] Error 1
win-make[2]: *** [descend] Error 2
win-make[1]: *** [dynlib] Error 2
win-make: *** [src] Error 2
```

**Comment by vszakats** [comment]
If a clean build doesn't resolve it please post your build settings and top of the log output (see details in point 9. [here](https://github.com/harbour/core/blob/master/README.md#troubleshooting)).

**Comment by NaldoDj** [comment]
####################################################
X86 (Build OK)

C:\GitHub\core>win-make.exe -B
! Building Harbour 3.2.0dev from source - http://harbour-project.org
! MAKE: win-make.exe 3.82 sh.exe  B
! HB_HOST_PLAT: win (x86_64)  HB_SHELL: nt
! HB_PLATFORM: win (x86) (autodetected)
! HB_COMPILER: mingw (autodetecteC: C:/TDM-GCC-32/bin/)
! Component: 'zlib' found in C:/GitHub/core/src/3rd/zlib (local)
! Component: 'pcre' found in C:/GitHub/core/src/3rd/pcre (local)
! Component: 'gpm' not supported on win platform
! Component: 'slang' not found. Configure with HB_WITH_SLANG.
! Component: 'curses' not found. Configure with HB_WITH_CURSES.
! Component: 'x11' not found. Configure with HB_WITH_X11.
! Component: 'wattcp/watt-32' not supported on win platform
...
! Finished package build...
./bin/win/mingw/hbmk2.exe ./config/postinst.hb first
! postinst script finished

----------------------------------------------------
####################################################
X86_64 (Build NOT OK)

C:\GitHub\core>SET HB_PATH=C:\GitHub\core\
C:\GitHub\core>SET MinGW64_PATH=C:\MinGW64\BIN\
C:\GitHub\core>SET PATH=%PATH%;%HB_PATH%
C:\GitHub\core>SET PATH=%PATH%;%MinGW64_PATH%
C:\GitHub\core>SET HB_CPU=x86_64
C:\GitHub\core>SET HB_PLATFORM=win
C:\GitHub\core>SET HB_COMPILER=mingw64
C:\GitHub\core>SET HB_CCPATH=%MinGW64_PATH%
C:\GitHub\core>SET HB_BUILD_VERBOSE=yes

C:\GitHub\core>win-make.exe -B
! Building Harbour 3.2.0dev from source - http://harbour-project.org
! MAKE: win-make.exe 3.82 sh.exe  B
! HB_HOST_PLAT: win (x86_64)  HB_SHELL: nt
! HB_PLATFORM: win (x86_64)
! HB_COMPILER: mingw64
! Component: 'zlib' found in C:/GitHub/core/src/3rd/zlib (local)
! Component: 'pcre' found in C:/GitHub/core/src/3rd/pcre (local)
! Component: 'gpm' not supported on win platform
! Component: 'slang' not found. Configure with HB_WITH_SLANG.
! Component: 'curses' not found. Configure with HB_WITH_CURSES.
! Component: 'x11' not found. Configure with HB_WITH_X11.
! Component: 'wattcp/watt-32' not supported on win platform
...
C:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -oleft.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../left.c
../../../../../bin/win/mingw64/harbour.exe ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../menuto.prg  -i../../../../../include -n1 -q0 -w3 -es2 -kmo -i- -l
C:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -omenuto.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\menuto.c
C:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -oxsavescr.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../xsavescr.c
../../../../../bin/win/mingw64/harbour.exe ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../checkbox.prg  -i../../../../../include -n1 -q0 -w3 -es2 -kmo -i- -l
C:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -ocheckbox.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\checkbox.c
C:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -ocdpapi.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../cdpapi.c
C:\MinGW64\BIN\gcc   -I. -I../../../../../include -W -Wall -O3  -DUNICODE  -ohbznet.o  -c ..\..\..\..\..\src\rtl\obj\win\mingw64\../../../hbznet.c
..\..\..\..\..\src\rtl\obj\win\mingw64\../../../hbznet.c:59:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
win-make.exe[3]: *** [..\..\..\..\..\src\rtl\obj\win\mingw64\hbznet.o] Error 1
win-make.exe[2]: *** [descend] Error 2
win-make.exe[1]: *** [dynlib] Error 2
win-make.exe: *** [src] Error 2
----------------------------------------------------
####################################################

**Comment by vszakats** [comment]
Corrupted source base?:
! HB_COMPILER: mingw (autodetecte**C**: C:/TDM-GCC-32/bin/)

Can't replicate with exact same settings as published above.

You can simplify these settings to:
```
C:\GitHub\core>SET PATH=C:\MinGW64\BIN\;%PATH%
C:\GitHub\core>win-make.exe
```

**Comment by NaldoDj** [comment]
I removed the previous build directory and after that the compilation work properly

thanks

C:\GitHub\core\if exist ".\bin\win\mingw64" (rmdir ".\bin\win\mingw64" /s /q)
C:\GitHub\core\if exist ".\lib\win\mingw64" (rmdir ".\lib\win\mingw64" /s /q)

C:\GitHub\core>SET PATH=C:\MinGW64\BIN\;%PATH%

C:\GitHub\core>win-make.exe
! Building Harbour 3.2.0dev from source - http://harbour-project.org
! MAKE: win-make.exe 3.82 sh.exe
! HB_HOST_PLAT: win (x86_64)  HB_SHELL: nt
! HB_PLATFORM: win (x86_64) (autodetected)
! HB_COMPILER: mingw64 (autodetected: C:/MinGW64/BIN/)
! Component: 'zlib' found in C:/GitHub/core/src/3rd/zlib (local)
! Component: 'pcre' found in C:/GitHub/core/src/3rd/pcre (local)
! Component: 'gpm' not supported on win platform
! Component: 'slang' not found. Configure with HB_WITH_SLANG.
! Component: 'curses' not found. Configure with HB_WITH_CURSES.
! Component: 'x11' not found. Configure with HB_WITH_X11.
! Component: 'wattcp/watt-32' not supported on win platform
win-make.exe[1]: Nothing to be done for `all'.
win-make.exe[1]: Nothing to be done for `all'.
! 'hbpmcom' library skipped (platform or compiler not supported)
...
! Finished package build...
./bin/win/mingw64/hbmk2.exe ./config/postinst.hb first
! postinst script finished
