### ISSUE TITLE
hbtcpio: returns HB_SOCKET_ERR_NOTINITIALISED on Windows (and possibly MS-DOS)

### ISSUE THREAD

**Issue by vszakats** [harbour/core#105]
`tcp:` virtual filename will not work on Windows, unless preceded 
by any `hb_socket*()` API call that internally invokes C-level `hb_socketInit()`.

```harbour
// Uncomment this to make it work
// hb_socketResolveAddr()

? hb_IsFunction( "HB_TCPIO" )  // -> .T.
? hb_vfOpen( "tcp:255.255.255.255:1" )  // -> NIL
? FError(), hb_socketErrorString( FError() )  // -> 62 ENOTINITIALIZED
```

**Comment by vszakats** [comment]
@druzus Hi Przemek, would you mind taking a look? It's easy to workaround once you realize what the problem is, but it's not the most clean or obvious solution.

**Comment by druzus** [comment]
Hi Viktor,

I remember about it.
I'll fix it together with HB_SOCKEX patch.
Probably on Monday or Tuesday.

best regards,
Przemek

**Comment by vszakats** [comment]
Thanks a lot!

**Comment by vszakats** [comment]
Thank you very much Przemek, the example code shows the fix to working fine, so I'm closing this.
