### ISSUE TITLE
MemoEdit() width is 1 charecter less than specified 

### ISSUE THREAD

**Issue by commandocoding** [harbour/core#116]
The memoedit function shows one less character than that is specified
causing the last character to be scrolling before the text wraps around.
test code below
```harbour
CLEAR
notes = "0123456789ABCDEF01234567890"
@1,1 to 5,11
MemoEdit( notes, 2, 2, 4, 10 )
```

**Comment by vszakats** [comment]
Did you compare it against original Cl*pper?

**Comment by vszakats** [comment]
It's Cl*pper compatible behavior.
