### ISSUE TITLE
Migrating Memos from Clipper 'S87 to Harbour, trouble with Soft-CR's in MEMOEDIT()

### ISSUE THREAD

**Issue by df7be** [harbour/core#117]
Full description of bug-report
[files-SOFT-Cr.zip](https://github.com/harbour/core/files/60510/files-SOFT-Cr.zip)
 in file report.txt in appended ZIP-Archive with sample code, test data and screenshots.
Many thanks, 73 es 55
Wilfried Brunken, DF7BE

**Comment by vszakats** [comment]
Would mind creating a short, self-contained, source-only example (pasted right here in the Issue) that demonstrates the problem? (I'm having a hard time processing all the extensive information in the `.zip`)
Also, can you confirm the problem using the latest Harbour revision?

**Comment by df7be** [comment]
Hello,i had a health problem, so my answer later, sorry
I tested it with the today's version from github under Ubuntu LINUX.
I put the case in a new ZIP-File (shortened h.prg).
Files:

HILFE.DBF
HILFE.DBT   The help database created and edited with HELPES87.EXE

h.prg         simple sample program
memoconv.prg  Source-Code for Memo-Converter

Screenshots:
k1.png      buggy screen
k2.png      correct appearance after onverting Soft-CR's to Hard-CR's
            ( and with Clipper S'87 )
k3.png      buggy screen under Ubuntu LINIX (Soft-CR's not visible)

Instructions for demonstrating the bug

- compile h.prg

- compile memoconv.prg

- start program h (opens the database "HILFE" (help) an displays the Memo-text of record 3

- look at k1.png:
  look at the Soft-CR's (lower i with grave) followed by another unprintable character.
  Press <ESC> to terminate

- make a backup copy of hilfe.dbf/dbt

- start the converter:
   memoconv hilfe.dbf
Memo converter: converts Clipper 'S87 Memos to Harbour
Copyright (c) 1999-2015 DF7BE
Number of fields 3
Memo field found: HTEXT
records converted :          240  RECNO :        240.0
C:\CLLOG\memotr\FEHLER~1>

- start program h again
  now it looks OK (k2.png)


It's a different behavior, so the Soft CR's are not visible, see image k3.png
[report_short.zip](https://github.com/harbour/core/files/90735/report_short.zip)
![k3](https://cloud.githubusercontent.com/assets/16278174/12331785/6f7c5f04-baeb-11e5-96e9-520fe206e8a1.png)

Now the Code Examples:
Code of h.prg, demonstrating the bug:
(see k1.png, opens database hilfe.dbf/.dbt)

----------------------------------
PROCEDURE MAIN


#ifdef __PLATFORM__WINDOWS
REQUEST HB_GT_WIN_DEFAULT
#endif 

REQUEST HB_LANG_DE
HB_LANGSELECT("DE")   && Codepage 850
REQUEST HB_CODEPAGE_DE850
set(_SET_CODEPAGE,"DE850")
SETMODE(25,80)

USE hilfe
GO 3 && according to picture k1.prg
 CLEAR SCREEN
 @ 3 , 5 TO 23 ,70 DOUBLE
 @ 6 , 6  SAY REPLICATE(CHR(196),64)
 @ 21, 6  SAY REPLICATE(CHR(196),64)

MEMOEDIT(HTEXT,7,6,20,69,.F.)
QUIT

RETURN
----------------------------------


Code Snippet of memoconv.prg
( converting all Soft CR's to HARD CR's )
-----------------------------------------
...
* start converting for every record
GO TOP
gel = 0


 KEYBOARD ""
 DO WHILE ( .NOT. EOF() ) .AND. LASTKEY() != 27
  l = RECNO()
  gel = gel + 1
  * within record for every memo field
            
  FOR i = 1 TO nmb_memos
    Feldname = memonamen[i] 
	  REPLACE &Feldname WITH HARDCR(&Feldname)
  NEXT
 * next record
  SKIP
 ENDDO
* give end message and terminate converting program 
...
-----------------------------------------

73 es 55 de DF7BE
 (best greetings and best success, HAM-Radio official abbreviatios)
