### ISSUE TITLE
Compiling Harbour on LINUX, missing symbolic links after "make install"

### ISSUE THREAD

**Issue by df7be** [harbour/core#118]
Hello,
making Harbour of actual GITHUB-Version:
(local as Linux userid "test")

 unzip core-master.zip 
cd core-master/
make
export HB_INSTALL_PREFIX=/home/test/hb
make install

add in ".profile" at the end:

#Eigene Erweiterungen
HB_INSTALL_PREFIX=/home/test/hb
export HB_INSTALL_PREFIX
PATH=$PATH:$HB_INSTALL_PREFIX/bin
export PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HB_INSTALL_PREFIX/lib
export LD_LIBRARY_PATH
#

log in new, so that the new entry is valid

Compiling the test "hello.prg"
test@afulap1:~/harbour/core-master/tests$ hbmk2 hello.prg 
hbmk2: Processing local make script: hbmk.hbm
Harbour 3.2.0dev (r1601141350)
Copyright (c) 1999-2015, http://harbour-project.org/
Compiling 'hello.prg'...
Lines 7, Functions/Procedures 1
Generating C source output to '/tmp/hbmk_7puXtn.dir/hello.c'... Done.
/usr/bin/ld: cannot find -lharbour
collect2: error: ld returned 1 exit status
hbmk2: Error: Running linker. 1

Running the hello sample:
test@afulap1:~/harbour/core-master/tests$ ./hello 
./hello: error while loading shared libraries: libharbour.so.3.2: cannot open shared object file: No such file or directory

setting the symbolic links:

cd ~/hb/lib
 ln -s libharbour.so.3.2.0 libharbour.so
ln -s libharbour.so.3.2.0 libharbour.so.3.2

and the program starts.

Please add the symbolic links in the makefile for "make install"

73 und 55 de DF7BE an many thanks

**Comment by vszakats** [comment]
For testing purposes (or using an interim build for production whatsoever) there is no need to use 'install' at all &mdash; the built result will be usable without it. As for 'install' to _system locations_ (which is the only scenario where creating symlinks would make sense), it is not recommended for interim builds, and adding symlinks does more harm than good in such situation, anyhow it _is_ done already by the install process, if you don't mind polluting your system with volatile software builds. If you want to install to system locations, there is also the option to create a `.deb`/`.rpm` package and install that package. To use interim builds on non-system locations, like in your example, it's best the manually configure `LD_LIBRARY_PATH` as you did above.
