### ISSUE TITLE
Wrong result by str(,,.t.) (using xhb.lib)

### ISSUE THREAD

**Issue by huabas** [harbour/core#120]
The following code produce "12.1234" instead of the expected result "12.12"

#include "xhb.ch"
 function main()
 dbcreate("test", {{"cost","n",10,4}})
 use test
 append blank
 field->cost := 12.1234
 ? str(cost,8,2,.t.)
return

**Comment by vszakats** [comment]
Fixed in 2016-01-14 11:02 UTC+0100 Przemyslaw Czerpak.
