### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by scippio** [harbour/core#122]
Platform: linux
After make:
```
../../../../../contrib/hbgs/core.c: In function ‘HB_FUN_HB_GS’:
../../../../../contrib/hbgs/core.c:85:35: error: ‘e_Quit’ undeclared (first use in this function)
          if( code == 0 || code == e_Quit )
                                   ^~~~~~
../../../../../contrib/hbgs/core.c:85:35: note: each undeclared identifier is reported only once for each function it appears in
hbmk2[hbgs]: Error: Running C/C++ compiler. 1
hbmk2[hbgs]: Exit code: 6: failed in compilation (Harbour, C compiler, Resource compiler)
! Finished package build...
```

**Comment by iezed** [comment]
Hi, any news for fixed this error?

**Comment by scippio** [comment]
No... I think it's something with ghostscript... but I don't know what... :(
https://github.com/harbour/core/blob/master/contrib/hbgs/core.c#L85-L90
http://www.ghostscript.com/doc/9.02/API.htm#return_codes

**Comment by scippio** [comment]
Ok... I change the ```e_Quit``` to actual ```gs_error_Quit``` and it's ok now :)
http://www.ghostscript.com/doc/current/API.htm#exit

**Comment by vszakats** [comment]
This has been fixed here (in the 3.4 fork): https://github.com/vszakats/harbour-core/commit/a49ec057c2b858e0519ab9adc6703e4c0062be2a

**Comment by scippio** [comment]
Ok. But other errors are also in your fork... :disappointed:

**Comment by vszakats** [comment]
Someone will have to reproduce and fix those who uses QT (I don't and CI tests [pass](https://travis-ci.org/vszakats/harbour-core/jobs/132218392)). Likely it's enough to tweak the build configuration, at first sight it appears the usual confusion of multiple QT versions installed in parallel. If you don't need `gtqtc`, just disable that specific contrib (details on README on how to do this), if you do, visit a forum where Harbour + QT users lurk and raise the issue with enough details to reproduce.

I recommend opening separate Issues for each specific problem you encounter, to make it possible to track and address them one by one.

**Comment by scippio** [comment]
Ok, thanks. When I disabled the QT... everything compiled alright. I think you can close this issue. Maybe later I open a new QT build issue... with some solution.
