### ISSUE TITLE
Travic-CI

### ISSUE THREAD

**Issue by scippio** [harbour/core#123]
"This is not an active repository"? https://travis-ci.org/harbour/core

**Comment by vszakats** [comment]
I ended up deleting it from my Travis CI account after failing permanently for several years. I keep maintaining Travis CI and AppVeyor CI builds under the 3.4 fork. Someone interested can merge this work over here and restore Travis CI functionality.

**Comment by tavinus** [comment]
Hi all.  
I am a bit confused about the status of things.  
  
@vszakats 's fork is 3.4 but is archived now.  
Was it merged here on master? Moved somewhere else?  
Does it mean that Travis CI can be fixed here as well?  
  
What version is the recommended latest to be used?   
I find so many old downloads. Very confusing...
Should I just compile it myself?

**Comment by tuffnatty** [comment]
There is Github Actions CI now.
