### ISSUE TITLE
Unrecoverable error 6005: Exception error

### ISSUE THREAD

**Issue by NaldoDj** [harbour/core#129]
## 2 ^ 13,466,917 generates a string with the size of 4,053,946 digits (https://en.wikipedia.org/wiki/Mersenne_prime). When trying to return this value to the Harbour the following error occurs:

Application Internal Error - D:\GitHub\tBigNumber\exe\win\mingw64\tBigNtst.exe
Terminated at: 2016-09-28 04:26:43
Info: tBigNumber
Unrecoverable error 6005: Exception error:

```
Exception Code:C0000005 ACCESS_VIOLATION
Exception Address:00000000004044BB
RAX:0000000000000001  RBX:00007FF5FED20018  RCX:0000000000000000  RDX:0000000000000001
RSI:000000000011413D  RDI:00007FF5FE750018  RBP:00000000003DDBBE
R8 :00000000001EEDDE  R9 :0000000000573FC2  R10:000000000026D0F4  R11:00007FF5FEB30017
R12:000000000000000A  R13:00007FF5FEB30018  R14:00000000001EEDDF  R15:00000000001DB7D8
CS:RIP:0033:00000000004044BB  SS:RSP:002B:00000000009EE970
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010287
Exception Parameters: 0000000000000000 00000000007E10B6
```

Modules:
0000000000400000 00000000003E1000 D:\GitHub\tBigNumber\exe\win\mingw64\tBigNtst.exe
00007FF9236E0000 00000000001CE000 C:\WINDOWS\SYSTEM32\ntdll.dll
00007FF922210000 00000000000AD000 C:\WINDOWS\System32\KERNEL32.DLL
00007FF920240000 000000000022E000 C:\WINDOWS\System32\KERNELBASE.dll
00007FF922490000 00000000000A2000 C:\WINDOWS\System32\ADVAPI32.dll
00007FF923120000 000000000009D000 C:\WINDOWS\System32\msvcrt.dll
00007FF920D50000 0000000000059000 C:\WINDOWS\System32\sechost.dll
00007FF922750000 000000000011B000 C:\WINDOWS\System32\RPCRT4.dll
00007FF922540000 0000000000030000 C:\WINDOWS\System32\GDI32.dll
00007FF9200C0000 000000000017D000 C:\WINDOWS\System32\gdi32full.dll
00007FF9225F0000 0000000000157000 C:\WINDOWS\System32\USER32.dll
000000005E6D0000 000000000001F000 C:\WINDOWS\System32\win32u.dll
0000000061440000 000000000001C000 C:\mg64\libgcc_s_seh-1.dll
000000006FC40000 0000000000100000 C:\mg64\libstdc++-6.dll
0000000064940000 0000000000015000 C:\mg64\libwinpthread-1.dll
00007FF923630000 000000000002D000 C:\WINDOWS\System32\IMM32.DLL
00007FF91E410000 0000000000093000 C:\WINDOWS\system32\uxtheme.dll
00007FF9231C0000 00000000002C7000 C:\WINDOWS\System32\combase.dll
00007FF91FE00000 00000000000F3000 C:\WINDOWS\System32\ucrtbase.dll
00007FF920050000 000000000006C000 C:\WINDOWS\System32\bcryptPrimitives.dll
00007FF9222D0000 000000000015B000 C:\WINDOWS\System32\MSCTF.dll
00007FF923000000 00000000000BD000 C:\WINDOWS\System32\OLEAUT32.dll
00007FF91FFB0000 000000000009A000 C:\WINDOWS\System32\msvcp_win.dll
00007FF91DF80000 0000000000026000 C:\WINDOWS\system32\dwmapi.dll
00007FF91FCB0000 000000000000F000 C:\WINDOWS\System32\kernel.appcore.dll

Called from TBIGNMULT(0) in ..\hbp..\src\common\tBigNumber.prg
Called from MULT(5212) in ..\hbp..\src\common\tBigNumber.prg
Called from TBIGNUMBER:MULT(1878) in ..\hbp..\src\common\tBigNumber.prg
Called from RECPOWER(5354) in ..\hbp..\src\common\tBigNumber.prg
Called from POWER(5293) in ..\hbp..\src\common\tBigNumber.prg
Called from TBIGNUMBER:POW(2366) in ..\hbp..\src\common\tBigNumber.prg
Called from TBIGNUMBER:IPOW(2388) in ..\hbp..\src\common\tBigNumber.prg
Called from TBIGNTST37(4293) in ..\hbp..\src\tests\tBigNtst.prg
Called from (b)GETTBIGNTST(767) in ..\hbp..\src\tests\tBigNtst.prg
Called from (b)TBIGNTST(616) in ..\hbp..\src\tests\tBigNtst.prg
Called from AEVAL(0)
Called from TBIGNTST(616) in ..\hbp..\src\tests\tBigNtst.prg

**Comment by NaldoDj** [comment]
Como resolver isso?
---------------------------
How to solve this?

**Comment by NaldoDj** [comment]
2:tBigNumber():iPow(7499983):OpDec()

[tBigNtst_20161014_10_51_30_653.zip](https://github.com/harbour/core/files/529985/tBigNtst_20161014_10_51_30_653.zip)

**Comment by NaldoDj** [comment]
2 ^ (7499983-1) é o maior valor que consigo calcular.
----------------------------------------------------------
2 ^ (7499983-1) is the highest value that can calculate.

**Comment by vszakats** [comment]
Possibly fixed in https://github.com/harbour/core/commit/35fe3becc791b259cd68561b572b82a4bfc3ee65. Reopen if still unresolved.

**Comment by NaldoDj** [comment]
Application Internal Error - C:\GitHub\tBigNumber\exe\win\mingw64\tBigNtst.exe
Terminated at: 2016-12-16 21:42:22
Info: tBigNumber
Unrecoverable error 6005: Exception error:

    Exception Code:C0000005 ACCESS_VIOLATION
    Exception Address:000000000040448B
    RAX:0000000000000002  RBX:00007FF5FF480078  RCX:0000000000000000  RDX:0000000000000002
    RSI:000000000011DED0  RDI:00007FF5FE8E0078  RBP:00000000003DDBBE
    R8 :00000000001EEDDE  R9 :0000000000577B82  R10:000000000028349A  R11:00007FF5FECC0077
    R12:000000000000000A  R13:00007FF5FECC0078  R14:00000000001EEDDF  R15:00000000001BCE38
    CS:RIP:0033:000000000040448B  SS:RSP:002B:00000000009FEA60
    DS:002B  ES:002B  FS:0053  GS:002B
    Flags:00010283
    Exception Parameters: 0000000000000000 00000000007FB01C

Modules:
0000000000400000 00000000003FB000 C:\GitHub\tBigNumber\exe\win\mingw64\tBigNtst.exe
00007FF82E070000 00000000001D1000 C:\WINDOWS\SYSTEM32\ntdll.dll
00007FF82C580000 00000000000AB000 C:\WINDOWS\System32\KERNEL32.DLL
00007FF82A560000 000000000021D000 C:\WINDOWS\System32\KERNELBASE.dll
00007FF828A80000 000000000007A000 C:\WINDOWS\system32\apphelp.dll
00007FF82B8C0000 00000000000A2000 C:\WINDOWS\System32\ADVAPI32.dll
00007FF82C630000 000000000009E000 C:\WINDOWS\System32\msvcrt.dll
00007FF82DE30000 0000000000059000 C:\WINDOWS\System32\sechost.dll
00007FF82DEA0000 0000000000121000 C:\WINDOWS\System32\RPCRT4.dll
00007FF82E030000 0000000000034000 C:\WINDOWS\System32\GDI32.dll
00007FF82AB00000 0000000000182000 C:\WINDOWS\System32\gdi32full.dll
00007FF82C310000 0000000000165000 C:\WINDOWS\System32\USER32.dll
00007FF82B5E0000 000000000001E000 C:\WINDOWS\System32\win32u.dll
0000000061440000 000000000001C000 C:\TDM-GCC-64\bin\libgcc_s_seh-1.dll
0000000064940000 0000000000015000 C:\TDM-GCC-64\bin\libwinpthread-1.dll
000000006FC40000 0000000000100000 C:\TDM-GCC-64\bin\libstdc++-6.dll
00007FF82C480000 000000000002E000 C:\WINDOWS\System32\IMM32.DLL
00007FF828C20000 0000000000095000 C:\WINDOWS\system32\uxtheme.dll
00007FF82BC10000 00000000002C8000 C:\WINDOWS\System32\combase.dll
00007FF82AA00000 00000000000F5000 C:\WINDOWS\System32\ucrtbase.dll
00007FF82AD40000 000000000006A000 C:\WINDOWS\System32\bcryptPrimitives.dll
00007FF82BAB0000 000000000015B000 C:\WINDOWS\System32\MSCTF.dll
00007FF82B600000 00000000000BF000 C:\WINDOWS\System32\OLEAUT32.dll
00007FF82B490000 000000000009C000 C:\WINDOWS\System32\msvcp_win.dll
00007FF828300000 0000000000026000 C:\WINDOWS\system32\dwmapi.dll
00007FF82A550000 000000000000F000 C:\WINDOWS\System32\kernel.appcore.dll

Called from TBIGNMULT(0) in ..\hbp\..\src\common\tBigNumber.prg
Called from MULT(6772) in ..\hbp\..\src\common\tBigNumber.prg
Called from TBIGNUMBER:MULT(2704) in ..\hbp\..\src\common\tBigNumber.prg
Called from RECPOWER(6950) in ..\hbp\..\src\common\tBigNumber.prg
Called from POWER(6875) in ..\hbp\..\src\common\tBigNumber.prg
Called from TBIGNUMBER:POW(3266) in ..\hbp\..\src\common\tBigNumber.prg
Called from TBIGNUMBER:IPOW(3295) in ..\hbp\..\src\common\tBigNumber.prg
Called from TBIGNTST38(4737) in ..\hbp\..\src\tests\tBigNtst.prg
Called from (b)GETTBIGNTST(870) in ..\hbp\..\src\tests\tBigNtst.prg
Called from (b)TBIGNTST(682) in ..\hbp\..\src\tests\tBigNtst.prg
Called from AEVAL(0)
Called from TBIGNTST(682) in ..\hbp\..\src\tests\tBigNtst.prg
Called from MAIN(330) in ..\hbp\..\src\tests\tBigNtst.prg
------------------------------------------------------------------------

**Comment by microvolution** [comment]
********************
portuguese:
Application Internal Error - G:\MVinfo\MIGRAR\SiCCA\SiCCA3604\sci10000\SiCCA3604.exe
Terminated at: 2018-02-20 07:50:10
Unrecoverable error 6005: Exception error:

    Exception Code:C0000005 ACCESS_VIOLATION
    Exception Address:0043160D
    EAX:00000000  EBX:00000003  ECX:00000179  EDX:000001F9
    ESI:00000000  EDI:006C3040  EBP:000DBA00
    CS:EIP:0023:0043160D  SS:ESP:002B:00CDFCC0
    DS:002B  ES:002B  FS:0053  GS:002B
    Flags:00010206
    Exception Parameters: 00000000 00001C3C
    CS:EIP: 8B 86 3C 1C 00 00 85 C0 0F 84 45 02 00 00 8B 40
    SS:ESP: 034344B4 00000000 00CDFCEC 00000000 00000021 00CDFCF4 02E761E4 02E76954 02E7697C 02E76954 02E761E4 034344B4 02E76954 00000039 006C3090 00CDFD3C

    C stack:
    EIP:     EBP:       Frame: OldEBP, RetAddr, Params...
    0043160D 000DBA00   75ADA15C 75ADA118 75ADA0FC 75ADA0DC 75ADA0C8 75ADA0A4 00CDF1F8 00000000 00000001 0B050DA5


Modules:
00400000 006DE000 G:\MVinfo\MIGRAR\SiCCA\SiCCA3604\sci10000\SiCCA3604.exe
77140000 0018D000 C:\WINDOWS\SYSTEM32\ntdll.dll
76F10000 000D0000 C:\WINDOWS\System32\KERNEL32.DLL
762F0000 001D7000 C:\WINDOWS\System32\KERNELBASE.dll
73D80000 00078000 C:\WINDOWS\System32\ADVAPI32.dll
73E00000 000BD000 C:\WINDOWS\System32\msvcrt.dll
770F0000 00043000 C:\WINDOWS\System32\sechost.dll
76E50000 000BE000 C:\WINDOWS\System32\RPCRT4.dll
75490000 00020000 C:\WINDOWS\System32\SspiCli.dll
75480000 0000A000 C:\WINDOWS\System32\CRYPTBASE.dll
764D0000 00057000 C:\WINDOWS\System32\bcryptPrimitives.dll
73A30000 000D4000 C:\WINDOWS\System32\COMDLG32.DLL
75750000 00246000 C:\WINDOWS\System32\combase.dll
73B10000 00117000 C:\WINDOWS\System32\ucrtbase.dll
75C20000 00088000 C:\WINDOWS\System32\shcore.dll
76B70000 00175000 C:\WINDOWS\System32\USER32.dll
76280000 00016000 C:\WINDOWS\System32\win32u.dll
765A0000 00022000 C:\WINDOWS\System32\GDI32.dll
73EC0000 0015E000 C:\WINDOWS\System32\gdi32full.dll
72DC0000 00211000 C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.248_none_5d7c08dba7db7edd\COMCTL32.DLL
76FE0000 0007C000 C:\WINDOWS\System32\msvcp_win.dll
75BD0000 00045000 C:\WINDOWS\System32\SHLWAPI.dll
74020000 01333000 C:\WINDOWS\System32\SHELL32.dll
75A30000 00038000 C:\WINDOWS\System32\cfgmgr32.dll
75CB0000 005C6000 C:\WINDOWS\System32\windows.storage.dll
75640000 0000E000 C:\WINDOWS\System32\kernel.appcore.dll
762A0000 00045000 C:\WINDOWS\System32\powrprof.dll
756C0000 00014000 C:\WINDOWS\System32\profapi.dll
75AD0000 000F7000 C:\WINDOWS\System32\ole32.dll
76D20000 00093000 C:\WINDOWS\System32\OLEAUT32.dll
72FE0000 00006000 C:\WINDOWS\SYSTEM32\MSIMG32.DLL
72310000 00022000 C:\WINDOWS\SYSTEM32\MSVFW32.DLL
6EF80000 00024000 C:\WINDOWS\SYSTEM32\WINMM.DLL
739C0000 0006C000 C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
6EB70000 00023000 C:\WINDOWS\SYSTEM32\WINMMBASE.dll
73990000 00030000 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
75450000 00019000 C:\WINDOWS\SYSTEM32\bcrypt.dll
76CF0000 00025000 C:\WINDOWS\System32\IMM32.DLL
65580000 002A9000 C:\WINDOWS\SYSTEM32\Msftedit.dll
72FF0000 00079000 C:\WINDOWS\system32\uxtheme.dll

Called from WVG_IMAGE(0)
Called from MAIN(238) in G:\MVinfo\MIGRAR\SiCCA\SiCCA3604\sci10000\pci10000.prg
------------------------------------------------------------------------
essa linha acima (MAIN 238) é a seguinte:
  Wvg_Image     ( 10 , 10 , 20 , 60 ,  , GOBJ_IMAGESOURCE_FILE, Splash , , .f. )  
sempre funcionou, até eu fazer uma mudança na compilação usando HB_GTSYS():
PROCEDURE HB_GTSYS() // função que faz a junção de modo CONSOLE(CUI) e GRÁFICOS(GUI), juntos num mesmo sistema.
   REQUEST HB_GT_WVG_DEFAULT // descobri que pra usar CONSOLE e GTWVW e HMG, sendo compilados pela IDE HMG 3.4.4, não precisa das demais linhas abaixo. 8/2/18w.
   // REQUEST HB_GT_WIN_DEFAULT
   REQUEST HB_GT_WVG
   // REQUEST HB_GT_WIN
RETURN
-----
Agora todo jeito que faço, coloco, tiro, não consigo mais executar o sistema.
Minha forma de compilar:
uso a IDE/HMG do Roberto Lopez versão 3.4.4 (que vem com o harbour 3.2) para compilar CONSOLE e GUI juntos, usando 2 libs gráficas:
- GTWVG para todo o programa (algumas telas incluem pushbutton, wvgimage, crtwvg, etc)
- estou construindo uma nova tela em 100% GUI usando o DEFINE/END WINDOW da HMG.

Alguém sabe resolver o problema, que não existia e passou a existir do nada?
grato,


***************
ENGLISH:
Application Internal Error - G:\MVinfo\MIGRAR\SiCCA\SiCCA3604\sci10000\SiCCA3604.exe
Terminated at: 2018-02-20 07:50:10
Unrecoverable error 6005: Exception error:

    Exception Code:C0000005 ACCESS_VIOLATION
    Exception Address:0043160D
    EAX:00000000  EBX:00000003  ECX:00000179  EDX:000001F9
    ESI:00000000  EDI:006C3040  EBP:000DBA00
    CS:EIP:0023:0043160D  SS:ESP:002B:00CDFCC0
    DS:002B  ES:002B  FS:0053  GS:002B
    Flags:00010206
    Exception Parameters: 00000000 00001C3C
    CS:EIP: 8B 86 3C 1C 00 00 85 C0 0F 84 45 02 00 00 8B 40
    SS:ESP: 034344B4 00000000 00CDFCEC 00000000 00000021 00CDFCF4 02E761E4 02E76954 02E7697C 02E76954 02E761E4 034344B4 02E76954 00000039 006C3090 00CDFD3C

    C stack:
    EIP:     EBP:       Frame: OldEBP, RetAddr, Params...
    0043160D 000DBA00   75ADA15C 75ADA118 75ADA0FC 75ADA0DC 75ADA0C8 75ADA0A4 00CDF1F8 00000000 00000001 0B050DA5


Modules:
00400000 006DE000 G:\MVinfo\MIGRAR\SiCCA\SiCCA3604\sci10000\SiCCA3604.exe
77140000 0018D000 C:\WINDOWS\SYSTEM32\ntdll.dll
76F10000 000D0000 C:\WINDOWS\System32\KERNEL32.DLL
762F0000 001D7000 C:\WINDOWS\System32\KERNELBASE.dll
73D80000 00078000 C:\WINDOWS\System32\ADVAPI32.dll
73E00000 000BD000 C:\WINDOWS\System32\msvcrt.dll
770F0000 00043000 C:\WINDOWS\System32\sechost.dll
76E50000 000BE000 C:\WINDOWS\System32\RPCRT4.dll
75490000 00020000 C:\WINDOWS\System32\SspiCli.dll
75480000 0000A000 C:\WINDOWS\System32\CRYPTBASE.dll
764D0000 00057000 C:\WINDOWS\System32\bcryptPrimitives.dll
73A30000 000D4000 C:\WINDOWS\System32\COMDLG32.DLL
75750000 00246000 C:\WINDOWS\System32\combase.dll
73B10000 00117000 C:\WINDOWS\System32\ucrtbase.dll
75C20000 00088000 C:\WINDOWS\System32\shcore.dll
76B70000 00175000 C:\WINDOWS\System32\USER32.dll
76280000 00016000 C:\WINDOWS\System32\win32u.dll
765A0000 00022000 C:\WINDOWS\System32\GDI32.dll
73EC0000 0015E000 C:\WINDOWS\System32\gdi32full.dll
72DC0000 00211000 C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.248_none_5d7c08dba7db7edd\COMCTL32.DLL
76FE0000 0007C000 C:\WINDOWS\System32\msvcp_win.dll
75BD0000 00045000 C:\WINDOWS\System32\SHLWAPI.dll
74020000 01333000 C:\WINDOWS\System32\SHELL32.dll
75A30000 00038000 C:\WINDOWS\System32\cfgmgr32.dll
75CB0000 005C6000 C:\WINDOWS\System32\windows.storage.dll
75640000 0000E000 C:\WINDOWS\System32\kernel.appcore.dll
762A0000 00045000 C:\WINDOWS\System32\powrprof.dll
756C0000 00014000 C:\WINDOWS\System32\profapi.dll
75AD0000 000F7000 C:\WINDOWS\System32\ole32.dll
76D20000 00093000 C:\WINDOWS\System32\OLEAUT32.dll
72FE0000 00006000 C:\WINDOWS\SYSTEM32\MSIMG32.DLL
72310000 00022000 C:\WINDOWS\SYSTEM32\MSVFW32.DLL
6EF80000 00024000 C:\WINDOWS\SYSTEM32\WINMM.DLL
739C0000 0006C000 C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
6EB70000 00023000 C:\WINDOWS\SYSTEM32\WINMMBASE.dll
73990000 00030000 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
75450000 00019000 C:\WINDOWS\SYSTEM32\bcrypt.dll
76CF0000 00025000 C:\WINDOWS\System32\IMM32.DLL
65580000 002A9000 C:\WINDOWS\SYSTEM32\Msftedit.dll
72FF0000 00079000 C:\WINDOWS\system32\uxtheme.dll

Called from WVG_IMAGE(0)
Called from MAIN(238) in G:\MVinfo\MIGRAR\SiCCA\SiCCA3604\sci10000\pci10000.prg
------------------------------------------------------------------------
this line above (MAIN 238) is as follows:
  Wvg_Image (10, 10, 20, 60,, GOBJ_IMAGESOURCE_FILE, Splash,, .f.)
always worked, until I make a change in the compilation using HB_GTSYS ():
PROCEDURE HB_GTSYS () // function that joins CONSOLE (CUI) and GRAPHICS (GUI) together on the same system.
   REQUEST HB_GT_WVG_DEFAULT // I found that to use CONSOLE and GTWVW and HMG, being compiled by IDE HMG 3.4.4, do not need the other lines below. 8/2 / 18w.
   // REQUEST HB_GT_WIN_DEFAULT
   REQUEST HB_GT_WVG
   // REQUEST HB_GT_WIN
RETURN
-----
Now every way I do, put, shoot, I can not run the system anymore.
My way to compile:
I use the IDE / HMG of Roberto Lopez version 3.4.4 (which comes with Harbor 3.2) to compile CONSOLE and GUI together, using 2 graphic libs:
- GTWVG for the whole program (some screens include pushbutton, wvgimage, crtwvg, etc)
- I'm building a new 100% GUI screen using HMG DEFINE / END WINDOW.

Does anyone know how to solve the problem, which did not exist and came to exist from nowhere?
thankful,
