### ISSUE TITLE
printing issue

### ISSUE THREAD

**Issue by KoshalAg** [harbour/core#132]
hi, 
I am using box and line command to print line and boxes but it do not appear same as on printer and on pdf pdf creator 
where a output to pdf creator is OK but on Printer it gets shift 1 or 2 char ahead or 1 or 2 lines down it keep changes on all kind of printer like on deskjet printer output is different and on laser printer output is different . please suggest me right way to use things .

koshal

**Comment by vszakats** [comment]
Hi, I suggest posting this to https://groups.google.com/forum/#!forum/harbour-users. Make sure to include example code or more details about the problem.
