### ISSUE TITLE
hbcurl not compiling 

### ISSUE THREAD

**Issue by ankitkuchhal2000** [harbour/core#138]
after setting path variable
path %path%d:\hb32\bin;d:\curl\bin;c:\openssl\bin

i am getting an error for
 -llibcurl not found
while using the following command to build

hbmk2 hbcurl.hbc ftp_uldl.prg

**Comment by alencar** [comment]
@ankitkuchhal2000 what happens when you do this steps?

SET HB_INSTALL_PREFIX=C:\hb32
SET HB_WITH_CURL=C:\Curl\include
SET HB_WITH_OPENSSL=C:\openssl\include

cd to harbour source tree
win-make.exe
win-make.exe install

cd to where you can find ftp_uldl.prg
hbmk2 hbcurl.hbc ftp_uldl.prg

**Comment by alcz** [comment]
Closing as it seems to be solved support question with no feedback.
