### ISSUE TITLE
Multiple compilers

### ISSUE THREAD

**Issue by lailton** [harbour/core#147]
I have on my computer:
MSVC 2012 32/64
MSVC 2015 32/64
MSVC 2017 32/64

How can I compile it and organize on binary folder?

I have tried use set HB_PLATFORM=vcxx / HB_PLATFORM=vcxx-64
but it is not reconigze.

I have too BCC55/BCC582/BCC700

What is suggestion for it?

**Comment by alcz** [comment]
You should use HB_BUILD_NAME= for the purpose. harbour-users mailing list is the more appropriate place for making basic questions.
