### ISSUE TITLE
Harbour on Linux Ubuntu

### ISSUE THREAD

**Issue by lailton** [harbour/core#148]
How can I compile the harbour for linux 32 inside linux ubuntu 64?

I have tried to use 

export HB_CPU=x86 

But the folder name is 32 but the binary is 64

**Comment by alcz** [comment]
Setting HB_USER_CFLAGS and HB_USER_LDFLAGS in the environment to -m32 may help, but i don't know how the libs are organized on your system. I don't feel if this doubt qualify for opening new issue too.
