### ISSUE TITLE
Security contact?

### ISSUE THREAD

**Issue by hartwork** [harbour/core#149]
Hi!

I would like to discuss a potential security issue with you. Where can I turn to for confidential reports? I haven't found security contact information for Harbour so far.

Thanks and best

Sebastian

**Comment by alcz** [comment]
If you can point out which source file have flaws then look up corresponding commits in https://github.com/harbour/core/blob/master/ChangeLog.txt 
to find out who is the module maintainer. Changelog entries are with e-mail addresses. That would be preferred method for now.

If you can't point out, then follow up and we settle on something else.

**Comment by hartwork** [comment]
Thanks for getting back to me this quickly.
The issue just turned out a non-issue (..).
If you plan on adding security contact information somewhere soon maybe keep the ticket open, else it can be closed as far as I am concerned.
