### ISSUE TITLE
Harbour iOS

### ISSUE THREAD

**Issue by lailton** [harbour/core#155]
I think that it is a bug.

I am making a hrb file and the parameter `-o` hbmk2 is not working.

How can I control the output for this file?

my `.hbp`
```
-gh
teste.prg
-inc
-obin\teste.bin
```
There's any solution for it?

**Comment by vszakats** [comment]
Fixed in 3.4 by making hbmk2 ignore `-inc` option when used together with `-gh`option. Incremental build in this combination is not supported at this time.
