### ISSUE TITLE
Harbour for Arduino

### ISSUE THREAD

**Issue by lailton** [harbour/core#156]
There's away to use harbour in an arduino device?

**Comment by druzus** [comment]
On Thu, 25 May 2017, Lailton Mariano wrote:

Hi,

> I have an app working file for Android version 5.0.0+
> And for android version <= 4.4.4 I have this issue:
> dlopen failed: cannot locate symbol "lstat64" referenced by "libharbour.so"

You try to use libharbour.so compiled with NDK dedicated for newer Android
versions which support native lstat64 function in GLIBC (in older versions
such calls were redirected to lstat during compilation)
Rebuild Harbour with android-ndk-*/platforms/android-9/arch-*
and take new libharbour.so

best regards,
Przemek
