### ISSUE TITLE
pb to built Harbour 3.2

### ISSUE THREAD

**Issue by djjdu** [harbour/core#168]
Hi,after two problems solved (zlib,pcre) impossible to
built harbour 3.2 ?
Thank for your help.
jj Duval
CD c:\CORE\CORE-MASTER

PATH=C:\hb32\comp\mingw\bin

SET  HB_WITH_ZLIB=C:\zlib

SET HB_WITH_PCRE=C:\pcre

SET HB_INSTALL_PREFIX=c:\harbour

WIN-MAKE  CLEAN INSTALL 

ined reference to `deflate'
../../../../../src/rtl/obj/win/mingw/hbznet_dyn.o:hbznet.c:(.text+0x1bbb): undef
ined reference to `deflateEnd'
../../../../../src/rtl/obj/win/mingw/hbznet_dyn.o:hbznet.c:(.text+0x1bc3): undef
ined reference to `inflateEnd'
../../../../../src/rtl/obj/win/mingw/hbznet_dyn.o:hbznet.c:(.text+0x1cf0): undef
ined reference to `deflate'
collect2.exe: error: ld returned 1 exit status
../../../../../config/dyn.mk:110: recipe for target 'harbour-32.dll' failed
WIN-MAKE[3]: *** [harbour-32.dll] Error 1
../../config/dyn.mk:106: recipe for target 'descend' failed
WIN-MAKE[2]: *** [descend] Error 2
../config/dir.mk:68: recipe for target 'dynlib.inst' failed
WIN-MAKE[1]: *** [dynlib.inst] Error 2
config/dir.mk:68: recipe for target 'src.inst' failed
WIN-MAKE: *** [src.inst] Error 2

c:\core\core-master>

**Comment by Petewg** [comment]
try  removing

>  SET HB_WITH_ZLIB=C:\zlib
>  SET HB_WITH_PCRE=C:\pcre

and see if it helps.

**Comment by djjdu** [comment]
Thank you. it's ok !
I put these two lines that had solved the first problems.
it therefore seems necessary to remove them before resuming the installation.
