### ISSUE TITLE
Open Watcom C compiler options are wrong

### ISSUE THREAD

**Issue by jmalak** [harbour/core#202]
The following Open Watcom C compiler options are wrong.
`-wcd124 -wcd136 -wcd201 -wcd367 -wcd368`
It is valid only for Open Watcom C++ compiler.
I recommend to remove them for C compiler options and use it only for C++ compiler or look into Open Watcom documentation and find appropriate message numbers for C compiler.
Open Watcom V2.0 C compiler has check on message numbers and will be reporting message numbers 367 and 368 as invalid.

**Comment by omm** [comment]
Ok, thanks.

**Comment by alcz** [comment]
I'll make some tests if we can successfully move C++ specific options to the cpp mode build (we can build in C or C++ alternatively). This Harbour branch/repo claims compatibility with old Watcom compilers too, so they should be retested such change.

**Comment by jmalak** [comment]
OW 2.0 should be compatible with older versions of OW on option level, some new options were added for new functionality.
Some new diagnostics were added that OW 2.0 can report additional warning and errors.
If you will use options valid for OW 1.9 then you should not have problem with OW 2.0.
The same for make files if you will use valid OW1.9 make files then it should work with OW2.0.

**Comment by alcz** [comment]
Thanks! Seems like -wcd124 -wcd136 -wcd201 -wcd367 -wcd368 were added to both wpp386 and wcc386:
https://github.com/harbour/core/commit/058d080c645c7e0220eeaa81a2c516200bd3b0a7#diff-b96607e9340e5d49a3fdbd79d94fd6b7
```
2010-12-17 02:00 UTC+0100 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
[...]
  * harbour/config/dos/watcom.mk
  * harbour/config/win/watcom.mk
  * harbour/config/linux/watcom.mk
  * harbour/config/os2/watcom.mk
    * disable explicitly some Open Watcom warnings in 3rd party code
      which we can safely ignore when HB_BUILD_WARN='no'

  * harbour/utils/hbmk2/hbmk2.prg
    * disable explicitly some Open Watcom warnings in 3rd party code
      which we can safely ignore when warning level is low
```
until:
https://github.com/harbour/core/commit/701acbb1168dff2b5ea26dacc44bc932cd9ffd1b#diff-b9e31f1166ac67b39a4ed1aee0c30de0
where it was changed with following
```
2011-03-01 02:06 UTC+0100 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
  * harbour/utils/hbmk2/hbmk2.prg
  * harbour/config/dos/watcom.mk
  * harbour/config/win/watcom.mk
  * harbour/config/linux/watcom.mk
  * harbour/config/os2/watcom.mk
    ! fixed to not use -wcd124 and -wcd136 in OpenWatcom C++ builds
```
So that we currently have:
```
wcc386 [...] -wcd124 -wcd136 -wcd201 -wcd367 -wcd368 
wpp386 [...] -wcd201 -wcd367 -wcd368 
```
which is quite confusing, when you tell they shouldn't be used with wcc386. Without the second mentioned commit i'd clearly just leave them in C++ mode, but now i don't know. I'll leave this for another day, but as 2010 was already OW 1.9 - i think we could trust you.

**Comment by jmalak** [comment]
These -wcd are exactly for  C++ compiler that they don't have sense for C compiler.
Don't use it for C compiler anyway.
Simple solution is to remove all -wcd option for C compiler command line then try to recompile the project. You will get some diagnostic messages from C compiler. You must analyse what they mean and if it is realy unwanted. What is unwanted can be disabled by -wcd option for C compiler. Number of message is in the for Wnnn where nnn is message number, first digit is warning level of message.

**Comment by jmalak** [comment]
Below i mesage number meaning for both compilers
`C++`
124 expression is too complicated
136 more than one calling convention has been specified
201 declaration statement follows an if statement
367 conditional expression in if statement is always true
368 conditional expression in if statement is always false
`C`
W124 Comparison result always %d
W136 Comparison equivalent to 'unsigned == 0'
W201 Unreachable code

message 367 and 368 is only for C++ compiler
message 124,136 and 201 could be for C compiler

**Comment by omm** [comment]
Ok, i make change in watcom.mk
```
ifneq ($(HB_BUILD_WARN),no)
   CFLAGS += -w3
else
   CFLAGS += -w1 -wcd124 -wcd136 -wcd201
   ifeq ($(HB_BUILD_MODE),cpp)
      CFLAGS += -wcd367 -wcd368
   endif
endif
```
and building goes on till the next error
```
harbour.y(47): Error! E1191: warning level must be an integer in range 0 to 5
harbour.y(48): Error! E1191: warning level must be an integer in range 0 to 5
```
from watcom docs
`
level
is a number from 0 to 5 (C compiler) or 0 to 9 (C++ compiler) and represents the level of the warning message`

how to set next
```
#elif defined( __WATCOMC__ )
#  pragma warning 13 9
#  pragma warning 368 9
```
for C and C++?

**Comment by jmalak** [comment]
It is same problem. C and C++ compiler use totaly different numbering/level schema.
If you  have code which is compiled by both C and C++ compiler then you need conditionaly included message change level.
But because previous version of C compiler doesn't support this pragma (ignore it), then these pragmas are only for C++ compiler. You should add conditional guard for C++ compiler over it if you compile by C compiler or if it is pure C code then you should remove it.

**Comment by jmalak** [comment]
I will check, because I think I fixed it already.
But maybe I overlook some place where this is Error.

**Comment by alcz** [comment]
Thank you very much for all the details!
Pragmas have been guarded already:
https://github.com/harbour/core/commit/b3d5e9a70b076bca7be95d8863d810140bd91173#diff-f1bbefd958010cc4eb3dfa328ae2bffc

**Comment by omm** [comment]
In harbour.y and harbour.yyc pragma defined only for C++, but for C level should be from 0 to 5.

**Comment by alcz** [comment]
Those warnings in harbour.y (13 and 365) were not applicable to C mode at all. Finally we will see how build tests go.

**Comment by omm** [comment]
Ok, now biulds ok, only warnings:
```
..\..\..\fm.c(167): Warning! W142: warning level must be an integer in range 0 to 5
..\..\..\fm.c(168): Warning! W142: warning level must be an integer in range 0 to 5
..\..\..\fm.c(169): Warning! W142: warning level must be an integer in range 0 to 5
..\..\..\fm.c(170): Warning! W142: warning level must be an integer in range 0 to 5
..\..\..\fm.c(214): Warning! W141: message number '13' is invalid
..\..\..\fm.c(215): Warning! W141: message number '367' is invalid
..\..\..\fm.c(216): Warning! W141: message number '368' is invalid
..\..\..\fm.c(217): Warning! W141: message number '887' is invalid
..\..\..\fm.c(218): Warning! W141: message number '887' is invalid
..\..\..\fm.c(475): Warning! W142: warning level must be an integer in range 0 to 5
..\..\..\fm.c(496): Warning! W141: message number '367' is invalid
```
In more places
```
Warning! W141: message number '367' is invalid
Warning! W141: message number '368' is invalid
```

**Comment by alcz** [comment]
Hopefully now it's cleaned up.

**Comment by jmalak** [comment]
I check a little bit your code and there is next thing which should be corrected even if it doesn't case any problem. It is luckily because message number exists in both compilers but with different meaning.
It is pragma disable_message or enable_message which refere to compiler message number.
Below is example from src/vm/fm.c source file.
`#pragma disable_message ( 201 )`
You need to guard it for appropriate compiler as other "message" relate pragmas.

**Comment by alcz** [comment]
Thanks! This seems very minor for now, i'll add it to the next commit. Waiting for the feedback of other Watcom users.

**Comment by omm** [comment]
Tested with
Open Watcom C/C++ x86 32-bit Compiler Driver Program
Version 2.0 beta Feb  5 2020 00:36:57 (32-bit)
Harbour https://github.com/harbour/core/commit/4041902a1963dd6c3927ade154985c3b1a7bc572
build OK, no more warnings.

Thanks @jmalak , @alcz
