### ISSUE TITLE
PROCEDURE/FUNCTION without RETURN keeps deeper return values

### ISSUE THREAD

**Issue by nchristophi** [harbour/core#209]
Dear Sirs

According to clippers manual: "If a user-defined function terminates without executing a RETURN statement, the return value is NIL."
https://www.itlnet.net/programming/program/Reference/c53g01c/ng10e2d2.html

This is not what I observe in the following code
`
Procedure Main()
local ret := func1()

? ret   // I get 1 instead of NIL
inkey(0)
return

Procedure Func1()
Func2()

Procedure Func2()
Func3()

Function Func3()
return 1
`

Is this normal in harbour?  Tested with both Harbour 3.20 and 3.40. The result is the same.

Thank you in advance.
Nikos Christophi

**Comment by tuffnatty** [comment]
The page you have referenced differentiates between procedures and
user-defined functions.

**Comment by nchristophi** [comment]
I get the same results with these code also.


Procedure Main()
local ret := func1()

? ret // I get 1 instead of NIL
inkey(0)
return

Function Func1()
Func2()

function Func2()
Func3()

Function Func3()
return 1

It does not matter if its a procedure or a Function.
If a returned value froma function is not accessed it is propagated to the calling procedure until someone access it.

Nikos

**Comment by alcz** [comment]
Such chained preservation of the return value is Clipper compatible behaviour. Try the original compiler yourself.

```
X:\CLIP53\BIN>NRET.EXE

DOS/16M Protected Mode Run-Time     Version 6.01
Copyright (C) Tenberry Software Inc. 1987 - 1994

         1                                       
````
