### ISSUE TITLE
Alert dialog box not showing up 

### ISSUE THREAD

**Issue by AhmedAmmarNegoudi** [harbour/core#214]
I'm using Harbour nightly on Win10 x64 i compiled a simple .prg file using hbmk2 that  .prg file contains alert dialog box but the dialog is not showing while it is returning values i faced the same problem even when i used the stable version 3.0.0

**Comment by AhmedAmmarNegoudi** [comment]
the content of my .prg file is :
//*********************************************************************************//
      local op      
      op:= alert("Choose one of the options", {" 1st option", " 2nd option"})
      DO CASE
      CASE op == 1
         @05,20 say   " 1st option" 
      Case op == 2
         @05,20 say   " 2nd option" 
      ENDCASE
//*******************************************************************************//
here is a screenshot of execution [https://imgur.com/vDeuFEz](url)

**Comment by alcz** [comment]
This is highly unlikely for a program compiled on Windows platform.

Please add the following to your program and paste the results:

```harbour
#include "hbgtinfo.ch"

? hb_gtVersion()
? hb_gtInfo( HB_GTI_ISSCREENPOS )
? hb_gtInfo( HB_GTI_KBDSUPPORT )
```

To force a real terminal during compilation use hbmk2.exe with -gtwin or -gtwvt parameter.

**Comment by AhmedAmmarNegoudi** [comment]
Before adding -gtwrt parameter the result was ::
WIN
.T.
.T.
MinGW GNU C 7.3 (32-bit)
but after adding it the dialog box shows normally 
Thanks

**Comment by alcz** [comment]
It should be also correct with GTWIN. But the Windows 10 console has many new options and variants of terminal. Can you make a screenshot of your Windows console settings?

**Comment by AhmedAmmarNegoudi** [comment]
Sadly i didn't understand what do you mean by Windows Console Settings but i think you mean this [https://imgur.com/1bFOAMt](https://imgur.com/1bFOAMt) notice that the language is french

**Comment by alcz** [comment]
You're good. Also the "Configuration" tab can be interesting candidate for another screenshot.

**Comment by AhmedAmmarNegoudi** [comment]
After adding setmode(25,80) with -gtwin the program works 
[https://imgur.com/z3Q9wyZ](https://imgur.com/z3Q9wyZ)

**Comment by alcz** [comment]
9001 rows setting is too much for the Alert() function. It is bypassed instead of being centered, where it wouldn't be visible anyway without scrolling. It is known and by design, but i don't remember what is the default number of rows in Windows 10 though.

**Comment by AhmedAmmarNegoudi** [comment]
Ok thank you very much
