### ISSUE TITLE
Compilation error in CygWin

### ISSUE THREAD

**Issue by rjopek** [harbour/core#215]
Compilation error in CygWin

```
but that doesn't matter either leaving: make
because compilation will fail:
I/home/harbour/hb32/src/3rd/zlib  -oclose.o  -c ../../../close.c
../../../close.c: In function ‘TIFFCleanup’:
../../../close.c:52:23: error: ‘O_RDONLY’ undeclared (first use in this function)
   52 |  if (tif->tif_mode != O_RDONLY)
      |                       ^~~~~~~~
../../../close.c:52:23: note: each undeclared identifier is reported only once for each function it appears in
```

[Harbour users](https://groups.google.com/g/harbour-users/c/qUU4wLMeU_Y)

**Comment by rjopek** [comment]
Will someone provide a competent answer or will there be support to Cygwin?

**Comment by omm** [comment]
Hi!

One more...

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-pc-cygwin/10/lto-wrapper.exe
Target: i686-pc-cygwin
Configured with: /mnt/share/cygpkgs/gcc/gcc.x86/src/gcc-10.2.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86/src/gcc-10.2.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=i686-pc-cygwin --host=i686-pc-cygwin --target=i686-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-arch=i686 --with-tune=generic --disable-sjlj-exceptions --enable-languages=c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC) 
! Building Harbour 3.2.0dev from source - https://harbour.github.io
! MAKE: win-make 4.1 c:/cygwin/bin/sh.exe clean install  
! HB_INSTALL_PREFIX: c:\dev\harbour_cygwin
! HB_BUILD_DYN: no
! HB_BUILD_CONTRIB_DYN: no
! HB_BUILD_SHARED: no
! HB_HOST_PLAT: win (x86)  HB_SHELL: nt
! LD_LIBRARY_PATH: C:/Dev/core/bin/cygwin/gcc:
! HB_PLATFORM: cygwin (x86) (auto-detected)
! HB_COMPILER: gcc (auto-detected: c:/cygwin/bin/)
! Component: 'zlib' found in C:/Dev/core/src/3rd/zlib (local)
! Component: 'pcre' found in C:/Dev/core/src/3rd/pcre (local)
! Component: 'gpm' not supported on cygwin platform
! Component: 'slang' not found. Configure with HB_WITH_SLANG.
! Component: 'curses' not found. Configure with HB_WITH_CURSES.
! Component: 'x11' not found. Configure with HB_WITH_X11.
! Component: 'wattcp/watt-32' not supported on cygwin platform
! GIT_REVISION: 492ae2a79b
...
gcc  -L../../../../../lib/cygwin/gcc   -o..\..\..\..\..\bin\cygwin\gcc\hbmk2.exe hbmk2.o -lhbextern -lhbdebug -lhbvmmt -lhbrtl -lhblang -lhbcpage -lgtcgi -lgtpca -lgtstd -lgttrm -lhbrdd -lrddntx -lrddnsx -lrddcdx -lrddfpt -lhbsix -lhbhsx -lhbusrrdd -lhbuddall -lhbrtl -lhbvmmt -lhbmacro -lhbcplr -lhbpp -lhbcommon -lhbpcre -lhbzlib -ldl -lpthread -lm -lrt -lhbmainstd 
/usr/lib/gcc/i686-pc-cygwin/10/../../../../i686-pc-cygwin/bin/ld: ../../../../../lib/cygwin/gcc/libhbzlib.a(gzlib.o):gzlib.c:(.text+0x3c1): undefined reference to `_wopen'
collect2: error: ld returned 1 exit status
../../../../../config/bin.mk:159: recipe for target 'hbmk2.exe' failed
win-make[3]: *** [hbmk2.exe] Error 1
../../config/bin.mk:155: recipe for target 'descend' failed
win-make[2]: *** [descend] Error 2
../config/dir.mk:68: recipe for target 'hbmk2.inst' failed
win-make[1]: *** [hbmk2.inst] Error 2
config/dir.mk:68: recipe for target 'utils.inst' failed
win-make: *** [utils.inst] Error 2

Regards

**Comment by rjopek** [comment]
Cygwin  provides a Unix-like environment and software tool set to users of any modern x86 32-bit and 64-bit versions of MS-Windows XP with SP3/Server 20xx/Vista/7/8/10 and using older versions of Cygwin some obsolete versions 95/98/ME/NT/2000/XP without SP3 as well. Cygwin consists of a Unix system call emulation library, cygwin1.dll, together with a vast set of GNU and other free software applications organized into a large number of optional packages. Among these packages are high-quality compilers and other software development tools, an X11 server, a complete X11 development toolkit, GNU emacs, Motif, TeX and LaTeX, OpenSSH client and server, and much more, including everything needed to compile and use software under MS-Windows. Is, anybody interested? I understand that no one. Harbour developers will not make changes for fear of the loss of stability for their business applications. No one is going to waste any time doing things that are not needed by the Harbour developers.

Close this issues.

**Comment by alcz** [comment]
If likely nobody is interested right now in patching the cygwin build system, it should stay IMHO, even if it's only a test harness.
This system is a unique excersise for Harbour codebase, because it's __PLATFORM__WINDOWS and __PLATFORM__UNIX at the same time.

Patches are welcome.

**Comment by rjopek** [comment]
All programming languages can, but Harbour can't.
> because it's __PLATFORM__WINDOWS and __PLATFORM__UNIX at the same time.
>

**Comment by alcz** [comment]
I don't think that making such statements in issue tracker makes sense whatsoever. Cygwin worked in the past, then use some old version, compare, contribute a patch for newer releases, stop making useless comments. Thank you.
