### ISSUE TITLE
HBMK2 and -L and HBC

### ISSUE THREAD

**Issue by JoseQuintas** [harbour/core#219]
Not sure if this can be considered a bug, a enhance or if can cause conficts with anything.
Need to declare hbc path before a hbc file

This ok: -L../..  hwgui.hbc

This not: hwgui.hbc -L../..

Note: file hwgui.hbc is on path ../..

**Comment by omm** [comment]
Hi!
Just specify full path to hbc (no matter what library it is, but you don't need to specify path for a core lib) without option -L, or explain your needs to declare hbc path before a hbc file.
And ../../hwgui.hbc is a path before hbc, is not it?

Best regards.

**Comment by JoseQuintas** [comment]
yes, there are several ways to do the same thing.
And once it has easy solutions, do not need to change hbmk2.
