### ISSUE TITLE
HBMK2: HBP name when using *.hbp

### ISSUE THREAD

**Issue by JoseQuintas** [harbour/core#228]
'''
> "d:\harbour\bin\hbmk2.exe" D:\harbour\addons\hwgui\hwgui\utils\debugger\*.hbp -ge1 -m -n -w3 -es2 -workdir=c:\temp
hbmk2: Processing environment options: -comp=mingw
hbmk2: Processing configuration: d:\harbour\bin\hbmk.hbc
Harbour 3.4.0dev (329aa1565e) (2021-01-18 00:35)
d:/harbour/comp/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: c:/temp/hwgdebug.o:hwgdebug.c:(.data+0x5b8): undefined reference to `HB_FUN_HB_OSPATHSEPARATOR'
collect2.exe: error: ld returned 1 exit status
hbmk2 [hwgdebug]: Error: Running linker. 1
gcc.exe c:/temp/hwgdebug.o c:/temp/hbmk_wk5qfq.o    -m32 -Wl,--nxcompat -Wl,--dynamicbase -Wl,--pic-executable,-e,_mainCRTStartup -mwindows -static -Wl,--start-group -Wl,-Bstatic -lhwgui_core -lhwgui_misc -lhwgui_hbxml -lhwgui_debug -lxhb -lhbwin -lpng -lhbextern -lhbdebug -lhbvmmt -lhbrtl -lhblang -lhbcpage -lgtcgi -lgtstd -lgtpca -lgtwin -lgtwvt -lgtgui -lhbrdd -lhbusrrdd -lrddntx -lrddcdx -lrddnsx -lrddfpt -lhbrdd -lhbhsx -lhbsix -lhbmacro -lhbcplr -lhbpp -lhbcommon -lhbmainwin -lkernel32 -luser32 -lgdi32 -ladvapi32 -lws2_32 -liphlpapi -lwinspool -lcomctl32 -lcomdlg32 -lshell32 -luuid -lole32 -loleaut32 -lmpr -lwinmm -lmapi32 -limm32 -lmsimg32 -lwininet -lhbpcre2 -lhbzlib -Wl,-Bdynamic   -Wl,--end-group -s -oD:/harbour/addons/hwgui/hwgui/utils/debugger/hwgdebug.exe  -Ld:/harbour/lib/win/mingw -Ld:/cdrom/fontes/integra/sefazclass -Ld:/cdrom/fontes/integra/libjpa -LD:/harbour/addons/hwgui/hwgui/lib/win/mingw

hbmk2: Hint: Add input file 'xhb.hbc' for missing Harbour function(s):
       hb_osPathSeparator()
hbmk2: Hint: Add input file 'hbobsolete.hbc' for missing Harbour function(s):
       hb_osPathSeparator()

> Process Exit Code: 7
> Time Taken: 00:02
'''

Here, I do not know HBP name

**Comment by omm** [comment]
Can you show what in `hbmk2: Processing configuration: d:\harbour\bin\hbmk.hbc` and `D:\harbour\addons\hwgui\hwgui\utils\debugger*.hbp`

**Comment by omm** [comment]
Just looking in `hwgui\utils` , i can't find any `debugger*.hbp`

**Comment by JoseQuintas** [comment]
on folder utils/debugger:
hwgdebug.hbp 
sample.hbp

**Comment by omm** [comment]
You are use
` D:\harbour\addons\hwgui\hwgui\utils\debugger*.hbp` 
maybe you mean the next
` D:\harbour\addons\hwgui\hwgui\utils\debugger\*.hbp`

For me `hbmk2 hwgui\utils\debbuger\*.hbp` works fine.
```
Harbour 3.2.0dev (r2011030937)
Copyright (c) 1999-2020, https://harbour.github.io/
Compiling 'hwgui\utils\debugger\hwgdebug.prg'...
Lines 6154, Functions/Procedures 63
Generating C source output to 'C:\Users\o2m\AppData\Local\Temp\hbmk_98pdws.dir\hwgdebug.c'... Done.
Harbour 3.2.0dev (r2011030937)
Copyright (c) 1999-2020, https://harbour.github.io/
Compiling 'hwgui\utils\debugger\sample.prg'...
Lines 3719, Functions/Procedures 2
Generating C source output to 'C:\Users\o2m\AppData\Local\Temp\hbmk_sa2air.dir\sample.c'... Done.
```

And what about `hbmk2: Processing configuration: d:\harbour\bin\hbmk.hbc`

**Comment by JoseQuintas** [comment]
harbour/bin/hbmk.hbc have my defaults: -w3 -es2 -m -n -q -ge1 compr=yes gui=yes mt=yes fullstatic=yes strip=yes and libpaths for some hbcs - only the path, do not add anything automatic
I am making a work with HBPs on hwgui, hmg, hmge extended and OOHG.
Because of several libraries and tests, I am making too many use of HBP, including compiling all at a time, with some levels of subprojects, but allways using containers, setup of projects are not shared.
-hbcontainer
project list
Calling hbmk2 from my text editor, I can click on error and edit any file of any folder.
If not on this way... it will be required much more time. 
Look compile using hbmk2 from text editor here: (Programmers Notepad)
https://www.youtube.com/watch?v=5vp_n8PevCg

**Comment by vinodvaya** [comment]
I think similar issue is with me as well, saying

Generating C source output to 'C:\users\...........\abcd.c' --- Done
GCC.EXE error: CreateProcess: No such file or directory
hbmk2: Error: Running C/C++ compiler. 1

Suggest what mistake I am making.

**Comment by JoseQuintas** [comment]
My issue is about to see each HBP name, but all works ok.
Check command line, and check if files are available - gcc.exe and c source.
Remember that you can use CLP as a HBP.

**Comment by vinodvaya** [comment]
Thanks for your reply and support.  I have checked command line and found ok, still can you guide of anythingis missing.

Hbmk2  @allprg.clp

Then the .C file is not getting created.

I am sharing snap of the same.

Thanks
Vimod



Thanks
Kumar



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JoseQuintas** [comment]
hbmk2 allprg.clp
and you can rename from .clp to .hbp 
but this issue is not the same as previous one.

**Comment by JoseQuintas** [comment]
Why close issue?
The wrong post is not about primary issue.

**Comment by vinodvaya** [comment]
Thanks .. Issue is still open as I am getting same messageeven after rename to .hbp

I am goingto share step by step command and results. Hope that will help.

Thank you so much.

Thanks
Kumar



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vinodvaya** [comment]
Please find snap.


Thanks
Kumar



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vinodvaya** [comment]
Problem is not resolved

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
