### ISSUE TITLE
HBMK2: -skip

### ISSUE THREAD

**Issue by JoseQuintas** [harbour/core#229]
What is the correct use of -skip?
On hbc is skip={win}
On hbp do not accept {win}-skip, -skip={win}, -skip:{win}

on doc:
```
hbp
-skip               skip processing the rest of the project file (filters not supported)

hbc
  skip=[msg]        skip processing the rest of the .hbc file. Display msg, if specified.
```

On GTWVG.HBC
```
skip={!allwin}
```

**Comment by omm** [comment]
Hi,Harbour has not option -skip, it's only in Viktor's fork of Harbour

**Comment by JoseQuintas** [comment]
Why not update it?
hbmk2 is ready for hb10, hb20, hb30, hb32, hb34 and xharbour

**Comment by JoseQuintas** [comment]
I think is a feature of harbour 3.2 too.
on harbour 3.2, gtwvg.hbc
```
skip={!win}
```

**Comment by JoseQuintas** [comment]
I am updating hwgui HBPs, and try to use -skip on HBPs for linux/windows.
Try using a hbmk.hbc on folder, defining in same way as GTWVG.HBC, but no success too.

**Comment by JoseQuintas** [comment]
Seems I get anything, but it do not cancel compression.
It skips but try compress an empty file at the end, if use compression.
Not a big problem, since nobody never use it until now.

**Comment by JoseQuintas** [comment]
Please, check about to change hbmk2.
Once primary use will be hwgui, to change only my local copy is not an option.
Pull request will include another changes, then I will only show my change.
https://github.com/JoseQuintas/harbour-32/commit/69b05ee2f269fc81086f6fa526d72d272d083165

**Comment by omm** [comment]
For all hbmk2 options run `hbmk2 -help >hbmk2.txt` and read the hbmk2.txt

And don't mix different version of Harbour.

**Comment by JoseQuintas** [comment]
I do not mix versions, on 3.2 and 3.4, the skip is used on GTWVG.
On both versions, I made same change on hbmk2.
May be it is not on hbmk2 doc, but it is in use.
Links to lines on harbour 3.2 hbmk2 source code, about skip
https://github.com/harbour/core/blob/master/utils/hbmk2/hbmk2.prg#L10632-10632
https://github.com/harbour/core/blob/master/utils/hbmk2/hbmk2.prg#L11404-11404

**Comment by JoseQuintas** [comment]
Ok, may be considered an undomented feature, 
https://github.com/harbour/core/blob/master/utils/hbmk2/doc/hbmk2.en.md
On Harbour 3.2 doc, only skip= exists.
