### ISSUE TITLE
Docs PRIVATE example gives error

### ISSUE THREAD

**Issue by Hovestar** [harbour/core#243]
On the docs, the code example for PRIVATE(https://harbour.github.io/doc/clc53.html#private-cmd) gives an error:

![image](https://user-images.githubusercontent.com/3644064/116419556-2e4f7d00-a80b-11eb-96e7-76b6d788f187.png)

I was looking at the docs since I get the same error for -w3. Is this a bad example or is something wrong?

**Comment by JoseQuintas** [comment]
when using compilation -w3 -es2, this requires variable declaration.
PRIVATE is not valid as a variable declaration, but defines as private.
On top of PRG, or inside a PROCEDURE/FUNCTION: 
MEMVAR aArray, aArray2, cColor, cChar
Not sure if this can be made on samples running on doc., but you can do on your source-code.
Best is to use LOCAL variable where possible, and MEMVAR for PUBLIC/PRIVATE where is not possible to use LOCAL

**Comment by alcz** [comment]
Clipper examples are unedited - even non standard comments make them fail. OTOH hbrun has the -w3 setting by default. You can toggle it with pragma though.
```harbour
#pragma -w -
   PRIVATE aArray := { 1, 2, 3, 4 }, ;
         aArray2 := Array(12, 24)
   PRIVATE cChar := Space(10), cColor := SetColor()
```
https://os.allcom.pl/hb/3.2-alcz/#!eJxTLihKTM9NVNAtV9DlUlBQCAjyDHMMcVVIdCwqSqxUsLJVqFYw1FEw0lEw1lEwUajVUbAGKYMAiCIjkCowS8MQqM7IRBPZoGTnjMQikIrggsTkVA1DA00doFh-Tj5EMLUEzNbQBAA75yNq
