### ISSUE TITLE
HARBOUR GT SYSTEM

### ISSUE THREAD

**Issue by rjopek** [harbour/core#252]
Hi,

Is there a possibility of creating a GT driver in order to use [GLFW](https://github.com/glfw/glfw) library’s in/out - of course in ~~GUI~~ graphics version. 

Also, is there a chance to make all of the updates to the newest version of the driver [gtalleg](https://github.com/harbour/core/tree/master/contrib/gtalleg)?

This questions is not being asked just by myself, but also by other young programmers who are looking to use libraries for graphics (OpenGL and Vulkan) with the usage of Harbour.

Best regards,
-- Rafał

**Comment by GamesForHarbour** [comment]
the harbor was orphaned from some library for games, as we had in the clipper, the dge5x is great for developing games
so the idea would be to port the allegro from C to use in the harbor , just as users have allegro ported to basic 

I have an average knowledge of the C language, I just don't know where to start, if any friend is willing to start the project, over time I will help, as I understand hb.api
