### ISSUE TITLE
Navigating files and directories for hbmk.hbm

### ISSUE THREAD

**Issue by rjopek** [harbour/core#255]
Why doesn't the hbmk.hbm file accept Unix/Linux output?

~~error:~~ no support?
```
./hbct.hbc
```

**Comment by JoseQuintas** [comment]
try:
-L./
hbct.hbc

or hbmk.hbc
libpaths=./
libs=hbct.hbc

note that path is related to hbm/hbc localization, not current path

**Comment by rjopek** [comment]
Thank you José, but it didn't help `-L./`
for proper operation, use `../`
why can't use `./`
