### ISSUE TITLE
Compare 2 string return wrong result

### ISSUE THREAD

**Issue by lailton** [harbour/core#260]
Hi, today I found a possible error checking 2 string with the "!=" 
It looks wrong to me. or Am I missing something?

```harbour
function main()

	local v1 := "11"
	local v2 := "1"

	? 'testing "1" != "11" is ' + if( "1" != "11", "different", "equal" )
	? 'testing "1" != "11" is ' + if( v1 != v2, "different", "equal" )

	? 'testing "1" <> "11" is ' + if( "1" <> "11", "different", "equal" )
	? 'testing "1" <> "11" is ' + if( v1 <> v2, "different", "equal" )

	? 'testing "1" == "11" is ' + if( "1" == "11", "equal", "different" )
	? 'testing "1" == "11" is ' + if( v1 == v2, "equal", "different" )

return nil
```

![Screen Shot 2022-04-19 at 19 16 26](https://user-images.githubusercontent.com/59419433/164110694-b374ab9c-cdcc-4024-b9d5-5e639a3ff4c3.png)

I was expecting for all return from condition be different.

**Comment by prgwiz** [comment]
What is your "set exact" setting?

**Comment by lailton** [comment]
Good catch, It was OFF.

Added ```set exact on```

Solved my problem.

thanks.

**Comment by fperillo** [comment]
? 'testing "1" != "11" is ' + if( v1 != v2, "different", "equal" )

It seems To me  that You inverte v1 And v2...

Il giorno Mer 20 Apr 2022 00:23 Lailton ***@***.***> ha
scritto:
