### ISSUE TITLE
Compile Error on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by df7be** [harbour/core#262]
Diagnostic text in attached text files

With regards,
Wilfried Brunken, DF7B
[Harbour_Compile_Error.txt](https://github.com/harbour/core/files/8676953/Harbour_Compile_Error.txt)
E

**Comment by alcz** [comment]
It may not resolve ~ to your home directory in all the contexts... Either it is the shell or make. Did you try changing:
HARBOUR_INSTALL=~/Harbour/core-master
to explicit
HARBOUR_INSTALL=/home/cltest/Harbour/core-master

**Comment by df7be** [comment]
Hello alcz,
MNI TNX for your quick response.
2nd try see appendend text file.

I am confused about this message:
make[4]: *** Keine Regel vorhanden, um das Ziel „auxtif“, 
  benötigt von „tiff“, zu erstellen.  Schluss.
"No rule existing building target "auxtif" , needed by "tiff". End
There is no package auxtif (like libauxtif-dev ...) existing.
Which package is missing ?

With regards
Wilfried Brunken, DF7BE

[HB-Compile-Error2.txt](https://github.com/harbour/core/files/8686462/HB-Compile-Error2.txt)

**Comment by alcz** [comment]
"auxtif" points to internal copy in /src/3rd/tiff - i think it's not a libtiff problem though

IMHO it looks like more general problem introduced  by GNU make 4.3 

I find this particular issue suspicious:

https://lists.gnu.org/archive/html/info-gnu/2020-01/msg00004.html

```
* WARNING: Backward-incompatibility!
  Previously appending using '+=' to an empty variable would result in a value
  starting with a space.  Now the initial space is only added if the variable
  already contains some value.  Similarly, appending an empty string does not
  add a trailing space.
```

Maybe we need /config/*.mk and Makefile's audit for ```+=``` usage.

**Comment by alcz** [comment]
Looking once again at your
https://github.com/harbour/core/files/8676953/Harbour_Compile_Error.txt

```HB_COMPILER=$HARBOUR_INSTALL``` seems completly wrong. It should express the flavour of the C compiler ```HB_COMPILER=gcc``` not the path.

Anyway it should be autodetected on Ubuntu 22. 
```apt install gcc``` is somehow missing on your system?

No visible problems with GNU Make 4.3.

**Comment by df7be** [comment]
Hello alcz,
i had success !
That's it:

HB_COMPILER=$HARBOUR_INSTALL seems completly wrong. It should express the flavour of the C compiler HB_COMPILER=gcc not the path.

Now for your installation instructions the recent settings in my .profile:

# --- Harbour and HWGUI --
   HARBOUR_INSTALL=/home/cltest/Harbour/core-master
   HWGUI_INSTALL=$HOME/svnwork/hwgui-code/hwgui
   PATH=$PATH:$HARBOUR_INSTALL/bin/linux/gcc:$HWGUI_INSTALL/bin
   export PATH
   LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HARBOUR_INSTALL/lib/linux/gcc
   export LD_LIBRARY_PATH
   HB_COMPILER=gcc
   export HB_COMPILER
   HB_INSTALL_PREFIX=$HARBOUR_INSTALL
   export HB_INSTALL_PREFIX
#

After this, i compiled Harbour, HWGUI and my app "CLLOG" with not problems.

make --version
GNU Make 4.3
Gebaut für x86_64-pc-linux-gnu

gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

I'll update the installation instructions for HWGUI as soon as possible.

apt install gcc is somehow missing on your system?
Yes, the gcc is installed with the default system.


I forever repeat:
MNI MNI MNI MNI MNI MNI MNI MNI TNX for this fantastic product !!!

With regards
73 es 55 de 
Wilfried Brunken, DF7BE

The issue can be closed.

**Comment by df7be** [comment]
Problem solved
