### ISSUE TITLE
TBROWSE class method SetColPos not moving to the right beyond columns currenctly shown

### ISSUE THREAD

**Issue by Numerabilis** [harbour/core#264]
TBrowse behavior in Harbour is different from xHarbour.
I have a function that works well in xHarbour but fails in Harbour because when I jump to the right with COLPOS it doesn´t go further.
So I decided to look inside both of them and I found out that **Harbour is not dealing with moving to the right beyond columns currenctly shown**.
Let´s see:
**The method SetColPos in Harbour is a little tiny code:**
```
METHOD setColPos( nColPos ) CLASS TBrowse

   IF ::nConfigure != 0
      ::doConfigure()
   ENDIF

   IF HB_ISNUMERIC( nColPos )
      ::nColPos := nColPos
   ELSE
      ::nColPos := 0
   ENDIF

   RETURN ::nColPos
```
**While this method in xHarbour is a little bigger and more complete:**
```
*------------------------------------------------------*
METHOD SetColPos( nColPos ) CLASS TBrowse
*------------------------------------------------------*

   default nColPos to 0

   if ::lNeverDisplayed .OR. (! ::lStable .AND. nColPos <= ::nRightVisible .AND. nColPos >= ::nLeftVisible)
      return ::nColPos := nColPos

   elseif nColPos <> 0 .AND. nColPos <> ::nColPos

      ::Moved()

      // I'm still inside columns currently shown
      if nColPos <= ::nRightVisible  .AND.;
         nColPos >= Max( ::nLeftVisible, ::nFrozenCols )

         ::nColPos := nColpos

      else
         // moving to the right
         if nColPos > ::nColPos

            if nColPos <= ::nColCount

               ::nRightVisible := nColPos
               ::nLeftVisible := ::LeftDetermine()
               ::nColPos := nColPos

            endif

         // moving to the left
         else

            if nColPos >= 1

               // Until the leftmost column has a number higher than the column I want to reach
               while ::nLeftVisible > nColPos

                  ::nRightVisible--
                  ::nLeftVisible := ::LeftDetermine()

               enddo

               ::nColPos := nColPos

            endif

         endif

         ::Invalidate()

      endif

      ::ForceStable()

   endif

Return ::nColPos
```
As we can see, the same code will have a different behavior between Harbour and xHarbour. I jus´t need somebody fix it so that I could migrate to Harbour.

**Comment by Numerabilis** [comment]
Hi, please disconsider this topic.
In spite of the same code have different behavior in Harbour I noticed that if I put FORCESTABLE() after :COLPOS() in Harbour the problem is gone.

**Comment by Petewg** [comment]
> Hi, please disconsider this topic. 

Hi,
It'd be preferable, to have opened this topic in harbour-users group,(_https://groups.google.com/g/harbour-users_), 
where such kind of issues usually are posted. Chances are,  you could have received better attention and advises
on how to resolve your problem. Also, since you said you're migrating from xHarbour to Harbour, I'd kindly suggest to take a look into this file: _https://github.com/harbour/core/blob/master/doc/xhb-diff.txt_ that might be proved helpful for your occasion.

regards,
Pete
