### ISSUE TITLE
HB_HCASEMATCH bug

### ISSUE THREAD

**Issue by nchristophi** [harbour/core#277]
Dear sirs.

I think hb_hcasematch(hash, .f.) has a bug. the flag is set only to the root hash. if you have any subkeys then those sub hashes do not respect this setting. Even if you add new sub-hash to the root hash. If this is by design then please close the ticket.
Please see the below code for replicating the issue.
Thank you in advance.
Nikos Christophi

PROCEDURE MAIN()
local hHash := {=>}

hHash["Key1"] := {=>}

hHash["Key1"]["Subkey1"] := "Value1"

altd()  //BreakPoint
? hb_HCaseMatch(hHash)      // .t.
? hb_hhaskey(hHash, "Key1") // .t.
? hb_hhaskey(hHash, "key1") // .f.
? hb_hhaskey(hHash["Key1"], "Subkey1") // .t.
? hb_hhaskey(hHash["Key1"], "subkey1") // .f.
hb_HCaseMatch(hHash, .f.)

? hb_HCaseMatch(hHash)      // .f.
? hb_HCaseMatch(hHash["Key1"]) //.t. should be .f.
? hb_hhaskey(hHash, "Key1") // .t.
? hb_hhaskey(hHash, "key1") // .t.
? hb_hhaskey(hHash["Key1"], "Subkey1") // .t.
? hb_hhaskey(hHash["Key1"], "subkey1") // .f.

hHash["Key2"] := {=>}
? hb_HCaseMatch(hHash["Key2"]) //.t. should be .f.

RETURN

**Comment by tuffnatty** [comment]
@nchristophi Hi. I don't think `hb_hCaseMatch` should work recursively on hash members. It's counterintuitive.
