### ISSUE TITLE
can't recompile harbour after msys2 clang64 openssl version upgrade

### ISSUE THREAD

**Issue by hbenrico** [harbour/core#293]
openssl maintaner suggested me to put in place HB_OPENSSL_NO_APPLINK definiktion, but still I am getting same compiling error.
I am getting this issue after an openssl upgrade (msys2)
many thanks in advance
Enrico

hbmk2: Compilazione in corso...
hbmk2: 'cd' su: ..\lib\win\mingw64\.hbmk\hbssl
hbmk2: Comando del compilatore C/C++:
gcc.exe -c -O3 -DHB_MEMO_SAFELOCK -DHB_OPENSSL_NO_APPLINK -DHBMK_HAS_OPENSSL -DOPENSSL_NO_IDEA -Iyes\..\inc32 -W -Wall -pipe -DUNICODE -D_UNICODE -I../../../../../include -Ic:/comp/msys64/clang64/include -std=gnu89 ../../../../../contrib/hbssl/ssl.c
../../../../../contrib/hbssl/ssl.c:105:13: fatal error: 'openssl/applink.c' file not found
   #include "openssl/applink.c"
            ^~~~~~~~~~~~~~~~~~~
1 error generated.
hbmk2[hbssl]: Error: Running C/C++ compiler. 1
gcc.exe -c -O3 -DHB_MEMO_SAFELOCK -DHB_OPENSSL_NO_APPLINK -DHBMK_HAS_OPENSSL -DOPENSSL_NO_IDEA -Iyes\..\inc32 -W -Wall -pipe -DUNICODE -D_UNICODE -I../../../../../include -Ic:/comp/msys64/clang64/include -std=gnu89 ../../../../../contrib/hbssl/ssl.c
hbmk2: 'cd' indietro.
hbmk2[hbssl]: Exit status: 6: fallimento nella compilazione (Harbour, compilatore C, compilatore delle Risorse)
! Finished package build and install...
mingw32-make[1]: *** [Makefile:8: install] Error 6

**Comment by alcz** [comment]
retry with -DOPENSSL_NO_APPLINK there is no equivalent under HB_* namespace, AFAIK

**Comment by hbenrico** [comment]
thank you!
unfortunately, it does not work :(
../../../../../contrib/hbssl/ssl.c:105:13: fatal error: 'openssl/applink.c' file not found
   #include "openssl/applink.c"
            ^~~~~~~~~~~~~~~~~~~
1 error generated.
thanks again
Enrico

**Comment by hbenrico** [comment]
since I compile with static libs, I saw that hbssl/ssl.c needs applink.c to be correctly compiled.
it seems that applink.c was removed from openssl maintainer.
any suggestion will be welcome :)
thanks in advance
Enrico

**Comment by hbenrico** [comment]
just to let you know, it ended up by copying this file: 
**https://github.com/openssl/openssl/blob/master/ms/applink.c**

to the folder:
**msys64/clang64/include/openssl**

**Comment by mlacecilia** [comment]
hi Enrico, thanks for the suggestion.
Strangely, I've found that applink.c isn't deleted in msys64/mingw32/include/openssl folder.
In effects Harbour builds fine in 32bit mode.
Anyway, reading the build log, I've found a lot of warnings about deprecated functions in hbssl lib, due to the update to 3.0.7
Probably a massive revision of the library will be mandatory in near future.
