### ISSUE TITLE
TBROWSEDB() ERROR AFTER LAST HARBOUR UPDATE

### ISSUE THREAD

**Issue by hbenrico** [harbour/core#313]
Error after calling tbrowsedb()for missing tbrowse class new() method 
thanks in advance

Callstack:
(b)MAIN(36)
TBROWSE:NEW(0)
TBROWSENEW(0)
TBROWSEDB(0)
OPENTB(442)
ELAB_PROD(755)
EC_INIT(512)
TRATT(118)
ECPROD(71)
(b)ROOTMENU(348)
EXECBUT(227)
|BUTLOOP(427)
XBUTREAD(151)
ROOTMENU(598)
MAIN(134)

DESCRIPTION  :No exported method
FILENAME     :
GENCODE      :13
OPERATION    :NEW
OSCODE       :0 
SEVERITY     :2
SUBSYSTEM    :BASE
TRIES        :0

**Comment by alcz** [comment]
Should not appear after 0477f62. Reopen if needed.
