### ISSUE TITLE
Compare issue

### ISSUE THREAD

**Issue by hoscarl** [harbour/core#348]
Hello
Maybe I'm wrong but if I compare these ( 927.59 =  927.59) same numbers I get false, this happens in any harbour xharbour hmg and clipper 5.3, platforms dos linux and windows.
What do I do wrong or is it a bug.
Code:
a1=850.01
a2=6.29
a3=11.00
a4=60.29
sub1 = a1+a2+a3+a4
sub2 = 927.59
if sub1 = sub2
    ? str(sub1)+str(sub2)
    ? "They are the same."
else
    ? str(sub1)+str(sub2)
    ? "THEY ARE NOT THE SAME !!!"
endif
Thank you.

**Comment by alcz** [comment]
This is how floating point unit operates on a CPU, not programming language issue.
Your example redacted below, to help you understand, that floating point numbers are not exact numbers.

```harbour
   LOCAL a1, a2, a3, a4, sub1, sub2

   a1 = 850.01
   a2 = 6.29
   a3 = 11.00
   a4 = 60.29
   sub1 = a1 + a2 + a3 + a4
   sub2 = 927.59
   ? Str( sub1, 29, 19 ), Str( sub2, 29, 19 )
   IF Round( sub1, 2 ) = Round( sub2, 2 )
      ? Str( sub1 ) + Str( sub2 )
      ? "They are the same."
   ELSE
      ? Str( sub1 ) + Str( sub2 )
      ? "THEY ARE NOT THE SAME !!!"
   ENDIF
```

result:
```
      927.5899999999999000000       927.5900000000000000000
       927.59       927.59
They are the same.
```
https://os.allcom.pl/hb/3.2/#!eJx9jLsKwkAQRfv9ihsrQ8KyO4mPLRYJErDwAWpjOZINCj4gj8K_d1eCdhZ3mDncOevdsliDdQomn8wnT9H2Z_2ZJFjb-URJpQWTnUoygjOrtVRKcG6nKpBQh_WWhCnhLOE8IPLI0ExOjFig7ZrxoCWTQhvE6RfSD4prjebZP6pvG7H3_BB90GAMlTgZNgp0dLy4F7hx6C4OLd-dHAl3a92fj1V5QrEvsd0d4Q8cik2JKIr846O61m-emUwX
