### ISSUE TITLE
Have the Color extensions to the tools been tested?

### ISSUE THREAD

**Issue by HBEnthusiast** [harbour/core#356]
Hi,

I've been trying to create and select windows with a different color scheme from the default, but there doesn't seem to be any difference.

I'm not sure if the 6th parameter in WOpen() is supposed to be a Color string or a number, so I tried both, to no avail.

```
nOutputWindow := wOpen(3,0,MAXROW()-5,MAXCOL()-2, .F.,5 , .T.)
nOutputWindow := wOpen(3,0,MAXROW()-5,MAXCOL()-2, .F.,""N/N+, BG+/B,,,N/N+" , .T.)
WSelect( OutputWindow_n )

```

The extensions are defined in ctwfunc.c, e.g.
```

HB_FUNC( WOPEN )
{
   int iColor;

   /* 6th (color) and 7th (lVisible) parameters are Harbour extensions */
   iColor = hb_ctColorParam( 6, -1 );   /* Harbour extension */ /* HB_EXTENSION */
   hb_retni( hb_ctwCreateWindow( hb_parni( 1 ), hb_parni( 2 ),
                                 hb_parni( 3 ), hb_parni( 4 ),
                                 hb_parl( 5 ), iColor,
                                 hb_parldef( 7, HB_TRUE ) ) ); /* HB_EXTENSION */
}

```

Maybe there's some configuration flag elsewhere, that tells the compiler to use the extensions, rather than the default Tools parameters.  So far, I haven't seen any behavior from using the functions that differs from the standard Clipper-compatible calls.

**Comment by Petewg** [comment]
There's no problem with WOpen(...) function; it's working exactly as intended.
I'd kindly suggest, prior to opening an issue here, please try to post your queries/questions
at harbour-users group (https://groups.google.com/forum/#!forum/harbour-users). 
Most probably, you'll get enough help to resolve your issues.
