### ISSUE TITLE
hbzebra: Array Bounds Issue in `_datamatrix_place_bit` (gcc warning analytics)

### ISSUE THREAD

**Issue by rjopek** [harbour/core#365]
@druzus In my environment, the warning about array bounds in the `_datamatrix_place_bit` function persists, caused by the lack of validation for the calculated indices iR and iC. I propose replacing the function with a version that includes additional index validation to eliminate the warning.

My proposal to change the function:
```c
static void _datamatrix_place_bit( int * pArr, int iPRow, int iPCol, int iR, int iC, int iValue )
{
   if( iR < 0 )
   {
      iR += iPRow;
      iC += 4 - ( ( iPRow + 4 ) % 8 );
   }
   if( iC < 0 )
   {
      iC += iPCol;
      iR += 4 - ( ( iPCol + 4 ) % 8 );
   }

   if( iR >= 0 && iR < iPRow && iC >= 0 && iC < iPCol )
   {
      pArr[ iR * iPCol + iC ] = iValue;
   }
   else
   {
      fprintf( stderr, "Error: Index out of bounds (iR: %d, iC: %d, iPRow: %d, iPCol: %d)\n", iR, iC, iPRow, iPCol );
   }
}
```

**Comment by druzus** [comment]
Hi,
This is a bug in GCC now the Harbour problem.
Whole s_size array is constant so it tires to "optimize" the calculation and predict results.
Unfortunately it does it in a wrong way.
It can be pacified by minor code change, i.e. it's enough to change the order of lines 295 and 296 and the warning disappears.
Other pseudo fix is adding at line 332:
   if( iPCol < 0 )
      iPCol = 0;
What of course is always false (the lowest value calculated in such way from s_size table is 8) but causes that GCC stops to show the warning.
Anyhow the real question is:
   Should we change valid code just to pacify the warning which are result of bug in C compiler?
I think that the author (Mindaugas) should answer.
It's also possible that there is real bug in some other logic and only GCC wrongly reports it. In such case we must not hide it but have to wait for real fix. Mindaugas is the best person to answer.

**Comment by rjopek** [comment]
The `if( iR >= 0 && iR < iPRow && iC >= 0 && iC < iPCol )` block ensures that the indices are within the array bounds. Thank you for reviewing the issue.

**Comment by alcz** [comment]
There is already similar check twice, though it lacks ```iR >= 0```.
```c
if( iR < iPRow && iC >= 0 && pArr[ iR * iPCol + iC ] == 0 )
   _datamatrix_place( pArr, iPRow, iPCol, iR, iC, i++ );
```
Could be moved to the body of ```_datamatrix_place```, but then the logic of incrementing ```i++``` has to be reviewed. I don't think we should care as much as this is a static function without the risk of being used outside of the context, so gcc analytics is not very much correct here.

**Comment by rjopek** [comment]
Can someone explain why this is closed?

```
/home/harbour/hb32/bin/linux/gcc/hbmk2 -quiet -width=0 -autohbm- @hbpre -inc hbzebra/hbzebra.hbp @hbpost
In function ‘_datamatrix_place_bit’,
    inlined from ‘_datamatrix_place_b’ at ../../../../../contrib/hbzebra/datamtrx.c:295:4,
    inlined from ‘_datamatrix_do_placement’ at ../../../../../contrib/hbzebra/datamtrx.c:346:10,
    inlined from ‘hb_zebra_create_datamatrix’ at ../../../../../contrib/hbzebra/datamtrx.c:486:4:
../../../../../contrib/hbzebra/datamtrx.c:260:28: warning: array subscript [-2147483648, -4] is outside array bounds of ‘int[2305843009213693951]’ [-Warray-bounds=]
  260 |    pArr[ iR * iPCol + iC ] = iValue;
      |    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In function ‘_datamatrix_do_placement’,
    inlined from ‘hb_zebra_create_datamatrix’ at ../../../../../contrib/hbzebra/datamtrx.c:486:4:
../../../../../contrib/hbzebra/datamtrx.c:333:21: note: at offset [-8589934592, -16] into object of size [4, 9223372036854775807] allocated by ‘hb_xgrab’
  333 |    pArr = ( int * ) hb_xgrab( sizeof( int ) * iPCol * iPRow );
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/harbour/hb32/bin/linux/gcc/hbmk2 -quiet -width=0 -autohbm- @hbpre -inc hbxpp/hbxpp.hbp @hbpost
```

After the suggested changes, it looks like this:

```
/home/harbour/hb32/bin/linux/gcc/hbmk2 -quiet -width=0 -autohbm- @hbpre -inc hbziparc/hbziparc.hbp @hbpost
/home/harbour/hb32/bin/linux/gcc/hbmk2 -quiet -width=0 -autohbm- @hbpre -inc hbzebra/hbzebra.hbp @hbpost
/home/harbour/hb32/bin/linux/gcc/hbmk2 -quiet -width=0 -autohbm- @hbpre -inc hbxpp/hbxpp.hbp @hbpost
```

**Comment by alcz** [comment]
Your suggested code changes just duplicate checks, without knowing where the problem is! Please read my message if you care, remove duplicate checks, then we could think about commiting something. Otherwise it's just unnecessary work and noise.
