### ISSUE TITLE
Copy and Past problem with some characters

### ISSUE THREAD

**Issue by ncroiset** [harbour/core#86]
When you copy a text with accents like â it does not appear on the text field GET of the application.
For example when you copy the word Théâtre it appear on the field as Thétre

**Comment by ncroiset** [comment]
This bug is not solved for me even with these parameters :

REQUEST HB_CODEPAGE_FR850
hb_cdpSelect("FR850")

The copy and past in GET field is working for characters like é but not â

**Comment by vszakats** [comment]
To confirm it as a bug, a self contained example would be needed that reproduces it.

**Comment by ncroiset** [comment]
No problem !

REQUEST HB_CODEPAGE_FR850
hb_cdpSelect("FR850")
clear screen
test = space(20)
@ 12,10 get test
read
@ 14,10 say "Result " + test
quit

Copy this word in the field : Théâtre

**Comment by vszakats** [comment]
I hope someone can reproduce this, but it can depend on the paste buffer cp which may depend on the paster app. Platform and GT is also unknown.

**Comment by ncroiset** [comment]
Windows XP and Windows 8 French same problem on both

**Comment by vszakats** [comment]
gt? Sender app?

**Comment by ncroiset** [comment]
Example notepad

**Comment by vszakats** [comment]
Gtwin / gtwvt / gtwvg?

**Comment by vszakats** [comment]
Also check first with head/dev/nightly branch first before reporting here, last release is very old.

**Comment by ncroiset** [comment]
I download the latest night build windows and compile my example with hbmk2, same problem.

**Comment by vszakats** [comment]
Which GT?

**Comment by ncroiset** [comment]
excuse me : gtwin

**Comment by marcobra** [comment]
FYI in Linux Ubuntu Harbour 3.2.0dev (r1501292255)  i confirm there isn't issue, copy and paste from your git main post page the word "Théâtre" (using Firefox or even using gedit editor) into field, then pressing return give me correct result: 
                                                                                                                                        
          Théâtre                                                                                                                            
                                                                                                                                             
          Result Théâtre

**Comment by ncroiset** [comment]
In my side :
C:\hb32\bin>harbour --version
Harbour 3.2.0dev (r1501292255)

If you want I can give the exe generated by hbmk2
to be more precise the â disapear in the get field during the past.
