### ISSUE TITLE
Upper case conversion not exactly as clipper 5.3

### ISSUE THREAD

**Issue by ncroiset** [harbour/core#87]
When you have a field like :
@ 12,3 GET xxx picture "!!!!"

The conversion of characters with accent is not made. On clipper 5.3 eg. à was translate to A é --> E
Today you obtain à ---> à, é --> é

**Comment by marcobra** [comment]
Please try to use a codepage:

    REQUEST HB_CODEPAGE_IT850
    hb_cdpSelect("IT850")
    clear screen
    do while .t.
        xxx="   "
       @ 12,3 GET xxx picture "!!!!"
       read
       ?xxx
    enddo

**Comment by ncroiset** [comment]
I try your example with these paramaters : 
REQUEST HB_CODEPAGE_FR850
hb_cdpSelect("FR850")
And it works. Thanks.
