### ISSUE TITLE
Can't send email using hbtip since a change

### ISSUE THREAD

**Issue by JoseQuintas** [harbour/core#90]
Since this change, I can't send emails using hbtip.

2015-01-29 23:55 UTC+0100 Jean Lefebvre (jfl/at/mafact.com)

I use same configuration for all accounts, using port 587.

More details can be found in:
https://github.com/vszakats/harbour-core/issues/109#issuecomment-78018002

Note
 I test with each version of Harbour 3.2, and confirm that until this change email was working ok.
(my normal use is Harbour 3.4)

**Comment by JoseQuintas** [comment]
I use FC.EXE to compare source code. Seems to me that this is the change that cause problem.
HBTIPANT=working sendmail
HBTIPATU=fail sendmail

**** HBTIPANT\sendmail.prg

      IF oInMail:OpenSecure()

         DO WHILE .T.
            IF ! oInMail:GetOk()
               EXIT
            ENDIF
            IF oInMail:cReply == NIL
               EXIT
            ELSEIF "LOGIN" $ oInMail:cReply
               lAuthLogin := .T.
            ELSEIF "PLAIN" $ oInMail:cReply
               lAuthPlain := .T.
            ELSEIF oInMail:HasSSL() .AND. "STARTTLS" $ oInMail:cReply
               lAuthTLS := .T.
            ELSEIF Left( oInMail:cReply, 4 ) == "250 "
               EXIT
            ENDIF
         ENDDO

         IF lAuthLogin
            IF ! oInMail:Auth( cUser, cSMTPPass )
***** HBTIPATU\sendmail.prg

      IF oInMail:OpenSecure( NIL, lSSL)

         lAuthTls := oInMail:lTLS 
 
         IF oInMail:lAuthLogin

            IF ! oInMail:Auth( cUser, cSMTPPass )

**Comment by druzus** [comment]
Please repeat your tests after 2015-03-12 09:41 UTC+0100.

**Comment by JoseQuintas** [comment]
No changes.

Additional information:
When ok, all sendmail work is made in less than 3 seconds.
When fail, need 10 seconds or more.

**Comment by druzus** [comment]
Please create self contain code example for Harbour core code and send it here or to me. This code should work with older Harbour version and fails with current one. Please reduce it to as small as possible example.
Your logs shows that in the test for new code authentication is disabled and "HELO" sent instead of "EHLO". Such behavior is controled by <lNoAuth> parameter. <lNoAuth> can be set only by user so without real example I can only say that it's result of wrong parameters passed by your code to hb_SendMail() function,

**Comment by JoseQuintas** [comment]
Sent direct to mail in changelog.txt, because of contain user/password.
Mail return with error message.

**Comment by druzus** [comment]
Hi Jose,
I haven't received any mail so far.
BTW I do not need real passwords. I'd like to see the test code because it looks that the problem is caused by parameters you passed to hb_sendMail() function.

**Comment by JoseQuintas** [comment]
'''
PROCEDURE Main
   LOCAL cFrom := "jpatec@terra.com.br"
   LOCAL cServer := "smtp.sao.terra.com.br"
   LOCAL cUser := "jpatec@terra.com.br"
   LOCAL cPassword := "wrongpassword"
   LOCAL cServerPop := "pop.sao.terra.com.br"
   LOCAL nPort := 587
   LOCAL nPriority := 3
   LOCAL lConfirm := .F.
   LOCAL lTrace := .T.
   LOCAL lTLS := .F.
   LOCAL nTimeOut := 20000
   LOCAL lNoAuth := .F.
   LOCAL acTo := { "jpatecnologia@mandic.com.br" }
   LOCAL acCC := {}
   LOCAL acBcc := {}
   LOCAL cFileBody := "tmp.txt"
   LOCAL cSubject := cFrom
   LOCAL acAttachment := {}
   LOCAL cReplyTo := NIL

   SetMode( 25, 80 )
   CLS
   hb_MemoWrit( "tmp.txt", "a single text" )
   ? "Sending mail"
   hb_SendMail( cServer, nPort, cFrom, acTo, acCc, acBcc, cFileBody, cSubject, acAttachment, cUser, cPassword, ;
      iif( Empty( cServerPop ), NIL, cServerPop ), nPriority, lConfirm, lTrace, .NOT. Empty( cServerPop ), ;
      lNoAuth, nTimeOut, cReplyTo, lTLS )
   RETURN
'''

**Comment by druzus** [comment]
Thanks for the example.
Please try after my recent commit.

**Comment by JoseQuintas** [comment]
Test and mail was sent, solved.
Thanks.
