### ISSUE TITLE
win_LoadBitmapFile() fails to load valid bitmap

### ISSUE THREAD

**Issue by vszakats** [harbour/core#91]
This displays zero, while it should be 3126:
```xbase
// download 'v_calend.bmp' to the current directory from
//   https://raw.githubusercontent.com/harbour/core/master/contrib/gtwvg/tests/v_calend.bmp

? Len( win_LoadBitmapFile( "v_calend.bmp" ) )
```

**Comment by alcz** [comment]
Original variable was hidden from scope by mistake in recent commit a10bfbda4058e19a1a2373993f6f491174677851
After 9a8b256d136fbd3c0b513b02fb3f31d917755b89 in my tree looks like it's OK.

**Comment by vszakats** [comment]
Nicely caught, thanks!

**Comment by vszakats** [comment]
Sorry, reopening till committed to the main branch. (the commit link made it appear to having been committed already).

**Comment by alcz** [comment]
The page which shows up is misleading. It looks like as it'd be from main branch indeed... Maybe i should have used another syntax in the comment(?)

**Comment by vszakats** [comment]
Yes, I if you paste a commit ID as is, it's assumed to belong to the repository it is used in, in this case the main one. To refer to a commit in a different branch, use the full URL: https://github.com/alcz/harbour/commit/9a8b256d136fbd3c0b513b02fb3f31d917755b89

[ I still don't understand however why the link itself works in the first scenario, when there is in fact no commit with that ID in that branch. ]
